buyer_stream:
  vertica:
    table: dma.vo_buyer_stream
    column_map:
      query: query_id
      item: item_id
      session: session_no
      cookie: cookie_id
      user: user_id
    dimensions:
      - platform_id
      - vertical_id
      - logical_category_id
      - category_id
      - subcategory_id
      - param1_id
      - param2_id
      - param3_id
      - param4_id
      - region_id
      - city_id
      - location_group_id
      - population_group
      - location_level_id
      - rec_engine_id
      - x_vertical_id
      - x_logical_category_id
      - x_category_id
      - x_subcategory_id
      - x_param1_id
      - x_param2_id
      - x_param3_id
      - x_param4_id
      - x_region_id
      - x_city_id
      - x_location_group_id
      - x_population_group
      - x_location_level_id
      - x_rec_engine_id
      - user_segment
      - is_asd
    participant: {visitor: cookie_id, user: user_id}
    dtm: event_date
    segm: cookie_id
  clickhouse:
    table: clickstream
    participant: {visitor: cookie_id, user: user_id}
    dtm: event_date

click_stream:
  vertica:
    table: dma.vo_clickstream
    column_map:
      session: session_no
      cookie: cookie_id
      user: user_id
    dimensions:
      - platform_id
      - vertical_id
      - logical_category_id
      - category_id
      - subcategory_id
      - param1_id
      - param2_id
      - param3_id
      - param4_id
      - region_id
      - city_id
      - location_group_id
      - population_group
      - location_level_id
    participant: {visitor: cookie_id, user: user_id}
    dtm: event_date
    segm: cookie_id

pageviews:
  vertica:
    table: dma.vo_clickstream_pageviews
    column_map:
      cookie: cookie_id
      user: user_id
    dimensions:
      - platform_id
      - vertical_id
      - logical_category_id
      - category_id
      - subcategory_id
      - param1_id
      - param2_id
      - param3_id
      - param4_id
      - region_id
      - city_id
      - location_group_id
      - population_group
      - location_level_id
    participant: {visitor: cookie_id, user: user_id}
    dtm: event_date
    segm: cookie_id

seller_item_active:
  vertica:
    table: dma.vo_seller_item_active
    column_map:
      item: item_id
    dimensions:
      - platform_id
      - vertical_id
      - logical_category_id
      - category_id
      - subcategory_id
      - param1_id
      - param2_id
      - param3_id
      - param4_id
      - region_id
      - city_id
      - location_group_id
      - population_group
      - location_level_id
      - user_segment
      - is_asd
      - user_segment_market
    participant: {user: user_id}
    dtm: event_date
    segm: user_id

seller_item_event:
  vertica:
    table: dma.vo_seller_item_event
    column_map:
      item: item_id
    dimensions:
      - platform_id
      - vertical_id
      - logical_category_id
      - category_id
      - subcategory_id
      - param1_id
      - param2_id
      - param3_id
      - param4_id
      - region_id
      - city_id
      - location_group_id
      - population_group
      - location_level_id
      - user_segment
      - is_asd
      - user_segment_market
      - location_id
      - microcat_id
    participant: {user: user_id}
    dtm: event_date
    segm: user_id

geo_loc_change:
  vertica:
    table: dma.vo_geo_loc_change
    column_map:
      item: item_id
      session: session_no
    dimensions:
      - platform_id
      - vertical_id
      - logical_category_id
      - category_id
      - subcategory_id
      - param1_id
      - param2_id
      - param3_id
      - param4_id
      - region_id
      - city_id
      - location_group_id
      - population_group
      - location_level_id
    participant: {visitor: cookie_id, user: user_id}
    dtm: event_date
    segm: cookie_id

geo_map_stream:
  vertica:
    table: dma.vo_geo_map_stream
    column_map:
      item: item_id
      session: session_no
    dimensions:
      - platform_id
      - vertical_id
      - logical_category_id
      - category_id
      - subcategory_id
      - param1_id
      - param2_id
      - param3_id
      - param4_id
      - region_id
      - city_id
      - location_group_id
      - population_group
      - location_level_id
    participant: {visitor: cookie_id, user: user_id}
    dtm: event_date
    segm: cookie_id

perf_mobile:
  vertica:
    table: dma.o_perf_mobile
    dimensions: [platform_id, network_type, is_core_content, screen_name, content_type]
    participant: {visitor: cookie_id, user: user_id}
    dtm: observation_date
    segm: cookie_id

perf_mobile_memory_warnings:
  vertica:
    table: dma.o_perf_memory_warnings
    dimensions: [platform_id, screen_name]
    participant: {visitor: cookie_id, user: user_id}
    dtm: event_date
    segm: cookie_id

perf_web:
  vertica:
    table: dma.o_perf_web
    dimensions: [platform_id, network_type, screen_name, stage_name]
    participant: {visitor: cookie_id, user: user_id}
    dtm: observation_date
    segm: cookie_id

core_contacts:
  vertica:
    table: dma.vo_core_contacts
    dimensions: [platform_id, vertical_id, logical_category_id, category_id, subcategory_id, param1_id, region_id, city_id, location_group_id, population_group, location_level_id, user_segment, price_group, is_asd]
    participant: {visitor: cookie_id, user: user_id}
    dtm: event_date
    segm: cookie_id_event_date

advert_funnel:
  vertica:
    column_map:
      session: session_hash
    table: dma.vo_advert_funnel
    dimensions: [platform_id, category_id, subcategory_id, vertical_id, logical_category_id]
    participant: {visitor: cookie_id, user: user_id}
    dtm: event_date
    segm: cookie_id

core_c2c:
  vertica:
    table: dma.vo_core_c2c
    dimensions: [platform_id, vertical_id, logical_category_id, category_id, subcategory_id, region_id, city_id, location_group_id, population_group, location_level_id, user_segment, is_asd]
    participant: {visitor: cookie_id, user: user_id}
    dtm: event_date
    segm: cookie_id

user_rating:
  vertica:
    table: dma.vo_user_rating
    dimensions: [vertical_id, logical_category_id]
    participant: {user: user_id}
    dtm: event_date
    segm: user_id

str:
  vertica:
    table: dma.vo_str
    dimensions: [platform_id, vertical_id, logical_category_id, category_id, subcategory_id, param1_id, param2_id, param3_id, param4_id, region_id, city_id, location_group_id, population_group, location_level_id]
    participant: {visitor: cookie_id, user: user_id}
    dtm: event_date
    segm: cookie_id

ratings:
  vertica:
    table: dma.vo_ratings
    dimensions: [platform_id, vertical_id, logical_category_id, category_id, subcategory_id, param1_id, param2_id, param3_id, param4_id, region_id, city_id, location_group_id, population_group, location_level_id]
    participant: {visitor: cookie_id, user: user_id}
    dtm: event_date
    segm: cookie_id

public_profile:
  vertica:
    table: dma.vo_public_profile
    dimensions: [platform_id]
    participant: {visitor: cookie_id}
    dtm: event_date
    segm: cookie_id

mnz_vas:
  vertica:
    table: dma.vo_mnz_vas
    dimensions: [platform_id, page_from, vertical_id, category_id, subcategory_id, logical_category_id, param1_id, param2_id, param3_id, param4_id, region_id, city_id, location_group_id, population_group, location_level_id, user_segment, is_asd, user_segment_market]
    participant: {visitor: cookie_id, user: user_id}
    dtm: event_date
    segm: cookie_id

mnz_lf:
  vertica:
    table: dma.vo_mnz_lf
    dimensions: [platform_id, vertical_id, logical_category_id, category_id, subcategory_id, region_id, city_id, location_group_id, population_group, location_level_id]
    participant: {user: user_id}
    dtm: event_date
    segm: user_id

messenger:
  vertica:
    table: dma.vo_messenger
    dimensions: [platform_id, appversion, vertical_id, category_id, subcategory_id, logical_category_id, param1_id, param2_id, param3_id, param4_id, region_id, city_id, location_group_id, population_group, location_level_id, user_segment, is_asd, user_segment_market]
    participant: {visitor: cookie_id, user: user_id}
    dtm: event_date
    segm: cookie_id

labor:
  vertica:
    table: dma.vo_labor
    column_map:
      session: session_no
    dimensions: [platform_id, vertical_id, logical_category_id, category_id, subcategory_id, param1_id, param2_id, param3_id, param4_id]
    participant: {visitor: cookie_id, user: user_id}
    dtm: event_date
    segm: cookie_id

express_cv:
  vertica:
    table: dma.vo_express_cv
    dimensions: [platform_id]
    participant: {user: user_id}
    dtm: event_date
    segm: user_id

delivery:
  vertica:
    table: dma.vo_delivery
    dimensions: [platform_id, vertical_id, category_id, subcategory_id, logical_category_id, is_intercity, param1_id, param2_id, param3_id, param4_id, region_id, city_id, location_group_id, population_group, location_level_id, user_segment, is_asd, user_segment_market]
    participant: {visitor: cookie_id, user: user_id}
    dtm: event_date
    segm: cookie_id

core_b2b:
  vertica:
    table: dma.vo_core_b2b
    dimensions: [platform_id, vertical_id, category_id, subcategory_id, logical_category_id, region_id, city_id, population_group, location_group_id, location_level_id, user_segment, is_asd]
    participant: {user: user_id}
    dtm: event_date
    segm: user_id

billing:
  vertica:
    table: dma.vo_billing
    dimensions: [platform_id]
    participant: {user: user_id}
    dtm: event_date
    segm: user_id

session_source:
  vertica:
    table: dma.vo_session_source
    dimensions:
      - platform_id
      - vertical_id
      - logical_category_id
      - category_id
      - subcategory_id
      - param1_id
      - param2_id
      - param3_id
      - param4_id
      - region_id
      - city_id
      - location_group_id
      - population_group
      - location_level_id
    participant:  {visitor: cookie_id}
    dtm: event_date
    segm: cookie_id

support:
  vertica:
    table: dma.vo_support
    dimensions: [platform_id]
    participant:  {visitor: cookie_id, user: user_id}
    dtm: event_date
    segm: cookie_id

perf_web_speed:
  vertica:
    table: dma.vo_perf_web_speed
    dimensions: [platform_id, region_id, city_id, location_group_id, from_page, population_group, location_level_id]
    participant: {visitor: cookie_id, user: user_id}
    dtm: event_date
    segm: cookie_id

cookie_account_enter:
  vertica:
    table: dma.vo_cookie_account_enter
    dimensions: [platform_id]
    participant: {visitor: cookie_id}
    dtm: event_date
    segm: cookie_id

favourite_sellers_totals:
  vertica:
    table: dma.favourite_sellers_totals
    participant: {user: user_id}
    dtm: event_date
    segm: user_id

communications:
  vertica:
    table: dma.vo_communications
    dimensions:
      - vertical_id
      - logical_category_id
      - category_id
      - subcategory_id
      - param1_id
      - param2_id
      - param3_id
      - param4_id
      - region_id
      - city_id
      - location_group_id
      - population_group
      - location_level_id
      - phone_location_group_id
      - phone_population_group
      - phone_location_level_id
      - phone_city_id
      - phone_region_id
    participant:  {user: user_id}
    dtm: event_date
    segm: user_id

image:
  vertica:
    table: dma.vo_image
    dimensions: [platform_id, network_type, screen_name]
    participant: {visitor: cookie_id, user: user_id}
    dtm: event_date
    segm: cookie_id

proprofile:
  vertica:
    table: dma.vo_proprofile
    dimensions: [platform_id, proprofile_traffic, proprofile_type, proprofile_version, tariff_type, tariff_subtype, tariffvertical_name]
    participant: {visitor: cookie_id, user: user_id}
    dtm: event_date
    segm: cookie_id

buyer_suggest:
  vertica:
    table: dma.vo_buyer_suggest
    dimensions:
      - platform_id
    participant: {visitor: cookie_id, user: user_id}
    dtm: event_date
    segm: cookie_id

seller_item_add:
  vertica:
      table: dma.vo_seller_item_add
      dimensions:
        - platform_id
      participant: {visitor: cookie_id, user: user_id}
      dtm: event_date
      segm: eventchain_id

seller_item_add_finish:
  vertica:
      table: dma.vo_seller_item_add_finish
      dimensions:
        - platform_id
      participant: {visitor: cookie_id, user: user_id}
      dtm: item_create_date
      segm: eventchain_id

support_ticket:
  vertica:
    table: dma.vo_support_ticket
    participant: {user: user_id}
    dtm: create_date
    segm: user_id

geo_map_labor:
  vertica:
    table: dma.vo_geo_map_labor
    dimensions:
      - platform_id
      - param1_id
      - param2_id
      - param3_id
      - param4_id
      - region_id
      - city_id
      - location_group_id
      - population_group
      - location_level_id
    participant:  {visitor: cookie_id, user: user_id}
    dtm: event_Date
    segm: cookie_id

buyer_call:
  vertica:
    table: dma.vo_buyer_call
    column_map:
      item: item_id
    dimensions: [platform_id, vertical_id, logical_category_id, category_id, subcategory_id, param1_id, param2_id, param3_id, param4_id, region_id, city_id, population_group]
    participant: {visitor: cookie_id, user: user_id}
    dtm: event_date
    segm: cookie_id

buyer_courier_order_create_date:
  vertica:
    table: dma.vo_courier_orders
    dimensions:
      - vertical_id
      - logical_category_id
      - category_id
      - subcategory_id
      - param1_id
      - param2_id
      - param3_id
      - param4_id
      - region_id
      - city_id
      - location_group_id
      - population_group
      - location_level_id
    participant: {user: buyer_id}
    dtm: create_date
    segm: courierorder_id

buyer_courier_order_status_date:
  vertica:
    table: dma.vo_courier_orders
    dimensions:
      - vertical_id
      - logical_category_id
      - category_id
      - subcategory_id
      - param1_id
      - param2_id
      - param3_id
      - param4_id
      - region_id
      - city_id
      - location_group_id
      - population_group
      - location_level_id
    participant: {user: buyer_id}
    dtm: status_date
    segm: courierorder_id

seller_courier_order_create_date:
  vertica:
    table: dma.vo_courier_orders
    dimensions:
      - vertical_id
      - logical_category_id
      - category_id
      - subcategory_id
      - param1_id
      - param2_id
      - param3_id
      - param4_id
      - region_id
      - city_id
      - location_group_id
      - population_group
      - location_level_id
    participant: {user: seller_id}
    dtm: create_date
    segm: courierorder_id

seller_courier_order_status_date:
  vertica:
    table: dma.vo_courier_orders
    dimensions:
      - vertical_id
      - logical_category_id
      - category_id
      - subcategory_id
      - param1_id
      - param2_id
      - param3_id
      - param4_id
      - region_id
      - city_id
      - location_group_id
      - population_group
      - location_level_id
    participant: {user: seller_id}
    dtm: status_date
    segm: courierorder_id

notification:
  vertica:
    table: dma.vo_notification
    dimensions: [platform_id]
    participant: {visitor: cookie_id, user: user_id}
    dtm: event_date
    segm: cookie_id

calltracking:
  vertica:
    table: dma.vo_calltracking
    dimensions:
      - vertical_id
      - region_id
      - city_id
      - location_group_id
      - population_group
      - location_level_id
    participant: {user: user_id}
    dtm: event_date
    segm: user_id

buyer_weighted:
  vertica:
    table: dma.vo_buyer_weighted
    dimensions: [platform_id, vertical_id, logical_category_id, logical_region, user_segment, price_group]
    participant: {visitor: cookie_id}
    dtm: event_date
    segm: cookie_id_event_date
    
app_call_bx:
  vertica:
    table: dma.vo_app_call_buyer
    column_map:
      item: item_id
      cookie: cookie_id
      user: user_id
    dimensions: [platform_id, vertical_id, logical_category_id, category_id, subcategory_id, param1_id, param2_id, param3_id, param4_id, region_id, city_id, population_group]
    participant: {visitor: cookie_id, user: user_id}
    dtm: event_date
    segm: event_date
    
app_call_sx:
  vertica:
    table: dma.vo_app_call_seller
    column_map:
      item: item_id
      cookie: cookie_id
      user: user_id
    dimensions: [platform_id, vertical_id, logical_category_id, category_id, subcategory_id, param1_id, param2_id, param3_id, param4_id, region_id, city_id, population_group]
    participant: {visitor: cookie_id, user: user_id}
    dtm: event_date
    segm: event_date

app_call_event:
  vertica:
    table: dma.vo_app_call_event
    column_map:
      item: item_id
      cookie: cookie_id
      user: user_id
    dimensions: [platform_id, vertical_id, logical_category_id, category_id, subcategory_id, param1_id, param2_id, param3_id, param4_id, region_id, city_id, population_group]
    participant: {visitor: cookie_id, user: user_id}
    dtm: event_date
    segm: event_date    

delivery_shipments_by_create_date:
  vertica:
    table: dma.vo_delivery_shipments
    column_map:
      item: item_id
    dimensions:
      - region_id
      - city_id
      - location_group_id
      - population_group
      - location_level_id
    participant: {user: buyer_id}
    dtm: create_date
    segm: shipment_id

delivery_shipments_by_status_date:
  vertica:
    table: dma.vo_delivery_shipments
    column_map:
      item: item_id
    dimensions:
      - region_id
      - city_id
      - location_group_id
      - population_group
      - location_level_id
    participant: {user: buyer_id}
    dtm: status_date
    segm: shipment_id

buyer_delivery_shipment_items_by_create_date:
  vertica:
    table: dma.vo_delivery_shipment_items
    column_map:
      item: item_id
    dimensions:
      - vertical_id
      - logical_category_id
      - category_id
      - subcategory_id
      - param1_id
      - param2_id
      - param3_id
      - param4_id
      - region_id
      - city_id
      - location_group_id
      - population_group
      - location_level_id
    participant: {user: buyer_id}
    dtm: create_date
    segm: shipment_id

buyer_delivery_shipment_items_by_status_date:
  vertica:
    table: dma.vo_delivery_shipment_items
    column_map:
      item: item_id
    dimensions:
      - vertical_id
      - logical_category_id
      - category_id
      - subcategory_id
      - param1_id
      - param2_id
      - param3_id
      - param4_id
      - region_id
      - city_id
      - location_group_id
      - population_group
      - location_level_id
    participant: {user: buyer_id}
    dtm: status_date
    segm: shipment_id

seller_delivery_shipment_items_by_create_date:
  vertica:
    table: dma.vo_delivery_shipment_items
    column_map:
      item: item_id
    dimensions:
      - vertical_id
      - logical_category_id
      - category_id
      - subcategory_id
      - param1_id
      - param2_id
      - param3_id
      - param4_id
      - region_id
      - city_id
      - location_group_id
      - population_group
      - location_level_id
    participant: {user: seller_id}
    dtm: create_date
    segm: shipment_id

seller_delivery_shipment_items_by_status_date:
  vertica:
    table: dma.vo_delivery_shipment_items
    column_map:
      item: item_id
    dimensions:
      - vertical_id
      - logical_category_id
      - category_id
      - subcategory_id
      - param1_id
      - param2_id
      - param3_id
      - param4_id
      - region_id
      - city_id
      - location_group_id
      - population_group
      - location_level_id
    participant: {user: seller_id}
    dtm: status_date
    segm: shipment_id