reports:
    - name: m42_services
      label: "Services"
      cubes_config: m42_services
      granularity: day
      dimensions_order:
        [
          platform,
          vertical,
          logical_category,
          logical_param1,
          logical_param2,
          is_asd,
          user_segment_market,
          category,
          subcategory,
          param1,
          param2,
          region,
        ]
      schedules:
        - {
          first_date: "$TODAY[-1]",
          last_date: '$TODAY[-1]',
        }

    - name: m42_services_monthly
      label: "Services monthly"
      cubes_config: m42_services
      granularity: month
      dimensions_order:
        [
          platform,
          vertical,
          logical_category,
          logical_param1,
          logical_param2,
          is_asd,
          user_segment_market,
          category,
          subcategory,
          param1,
          param2,
          region,
        ]
      schedules:
        - {
          first_date: '$START_OF_MONTH[-1]',
          last_date: '$END_OF_MONTH[-1]',
          schedule_interval: { day_month: 1 },
        }