buyer_stream:
  vertica:
    table: dma.vo_buyer_stream
    column_map:
      query: query_id
      x_query: x_query_id
      item: item_id
      session: session_no
      cookie: cookie_id
      user: user_id
    dimensions:
      - vertical_id
      - logical_category_id
      - category_id
      - subcategory_id
      - param1_id
      - param2_id
      - param3_id
      - param4_id
      - region_id
      - city_id
      - location_group_id
      - population_group
      - location_level_id
      - rec_engine_id
      - x_vertical_id
      - x_logical_category_id
      - x_category_id
      - x_subcategory_id
      - x_param1_id
      - x_param2_id
      - x_param3_id
      - x_param4_id
      - x_region_id
      - x_city_id
      - x_location_group_id
      - x_population_group
      - x_location_level_id
      - x_rec_engine_id
    participant: {visitor: cookie_id, user: user_id}
    dtm: event_date
    segm: cookie_id

click_stream:
  vertica:
    table: dma.vo_clickstream
    column_map:
      session: session_no
      cookie: cookie_id
      user: user_id
    dimensions:
      - vertical_id
      - logical_category_id
      - category_id
      - subcategory_id
      - param1_id
      - param2_id
      - param3_id
      - param4_id
      - region_id
      - city_id
      - location_group_id
      - population_group
      - location_level_id
    participant: {visitor: cookie_id, user: user_id}
    dtm: event_date
    segm: cookie_id

seller_item_active:
  vertica:
    table: dma.vo_seller_item_active
    column_map:
      item: item_id
    dimensions:
      - vertical_id
      - logical_category_id
      - category_id
      - subcategory_id
      - param1_id
      - param2_id
      - param3_id
      - param4_id
      - region_id
      - city_id
      - location_group_id
      - population_group
      - location_level_id
    participant: {user: user_id}
    dtm: event_date
    segm: user_id

seller_item_event:
  vertica:
    table: dma.vo_seller_item_event
    column_map:
      item: item_id
    dimensions:
      - vertical_id
      - logical_category_id
      - category_id
      - subcategory_id
      - param1_id
      - param2_id
      - param3_id
      - param4_id
      - region_id
      - city_id
      - location_group_id
      - population_group
      - location_level_id
    participant: {user: user_id}
    dtm: event_date
    segm: user_id

geo_loc_change:
  vertica:
    table: dma.vo_geo_loc_change
    column_map:
      item: item_id
      session: session_no
    dimensions:
      - vertical_id
      - logical_category_id
      - category_id
      - subcategory_id
      - param1_id
      - param2_id
      - param3_id
      - param4_id
      - region_id
      - city_id
      - location_group_id
      - population_group
      - location_level_id
    participant: {visitor: cookie_id, user: user_id}
    dtm: event_date
    segm: cookie_id

geo_map_stream:
  vertica:
    table: dma.vo_geo_map_stream
    column_map:
      item: item_id
      session: session_no
    dimensions:
      - vertical_id
      - logical_category_id
      - category_id
      - subcategory_id
      - param1_id
      - param2_id
      - param3_id
      - param4_id
      - region_id
      - city_id
      - location_group_id
      - population_group
      - location_level_id
    participant: {visitor: cookie_id, user: user_id}
    dtm: event_date
    segm: cookie_id

perf_mobile:
  vertica:
    table: dma.o_perf_mobile
    dimensions: [network_type, is_core_content, screen_name, content_type]
    participant: {visitor: cookie_id, user: user_id}
    dtm: observation_date
    segm: cookie_id

perf_web:
  vertica:
    table: dma.o_perf_web
    dimensions: [network_type, screen_name, stage_name]
    participant: {visitor: cookie_id, user: user_id}
    dtm: observation_date
    segm: cookie_id

core_contacts:
  vertica:
    table: dma.vo_core_contacts
    dimensions: [vertical_id, logical_category_id, category_id, subcategory_id, param1_id, region_id, city_id, location_group_id, population_group, location_level_id]
    participant: {visitor: cookie_id}
    dtm: event_date
    segm: cookie_id_event_date

advert:
  vertica:
    column_map:
      session: session_no
    table: dma.vo_advert
    dimensions: [category_id, subcategory_id]
    participant: {visitor: cookie_id, user: user_id}
    dtm: event_date
    segm: cookie_id

core_c2c:
  vertica:
    table: dma.vo_core_c2c
    dimensions: [vertical_id, logical_category_id, category_id, subcategory_id, region_id, city_id, location_group_id, population_group, location_level_id]
    participant: {visitor: cookie_id, user: user_id}
    dtm: event_date
    segm: cookie_id
