metric.ratio:
  appcall_anon_per_pv_btn:                 {num: appcall_anon_bx_outgoing_itemview, den: phone_view_button_clicks}
  appcall_anon_per_pv_btn_user:            {num: user_appcall_anon_per_pv_btn_user, den: users_pv_button_clicks}
  appcall_anon_success_per_pv_btn:         {num: cnt_appcall_anon_success_per_pv_btn_user, den: phone_view_button_clicks}
  appcall_anon_success_per_pv_btn_user:    {num: user_appcall_anon_success_per_pv_btn_user, den: users_pv_button_clicks}

