metric.counter:
  btc_funnel_first:                        {filter: {$or: [{<<: *is_fav}, {<<: *is_msg_btn}, {<<: *is_ph_tot}]}}

metric.uniq:
  users_btc_funnel_first:                  {counter: btc_funnel_first,                key: [user]}
  sess_btc_funnel_first:                   {counter: btc_funnel_first,                key: [user, session]}

