metric.ratio:
  ad_pages_to_contact:                     {num: ad_pages_to_contact,             den: buyers}
  correct_and_map_searches_and_iv_to_contact: {num: correct_and_map_searches_and_iv_to_contact, den: buyers}
  correct_searches_and_iv_to_contact:      {num: correct_searches_and_iv_to_contact, den: buyers}
  correct_searches_to_contact:             {num: correct_searches_to_contact,     den: buyers}
  item_views_to_contact:                   {num: item_views_to_contact,           den: buyers}
  map_searches_and_iv_to_contact:          {num: map_searches_and_iv_to_contact,  den: buyers}
  map_searches_to_contact:                 {num: map_searches_to_contact,         den: buyers}
  searches_and_item_views_to_contact:      {num: searches_and_iv_to_contact,      den: buyers}
  searches_to_contact:                     {num: searches_to_contact,             den: buyers}

