metric.counter:
  btc_funnel_first:                        {obs: [favorites_added, phone_views_total, realty_development_phone_views, total_delivery_click, write_button_clicks]}

metric.uniq:
  users_btc_funnel_first:                  {counter: btc_funnel_first,                key: [user]}
  sess_btc_funnel_first:                   {counter: btc_funnel_first,                key: [user, session]}

