metric.counter:
  btc_funnel_second:                       {obs: [answered_proxy_calls, booking_created_short_rent, call_phone_screen_views_client, delivery_order_created, first_messages, missed_proxy_calls]}

metric.uniq:
  users_btc_funnel_second:                 {counter: btc_funnel_second,               key: [user]}
  sess_btc_funnel_second:                  {counter: btc_funnel_second,               key: [user, session]}

metric.ratio:
  calls_per_phone_views:                   {num: calls,                           den: phone_views_total}

