metric.counter:
  bt_clicks_new:                           {filter: {$or: [{<<: *is_booking}, {<<: *is_delivery}, {<<: *is_fav}, {<<: *is_msg_btn}, {<<: *is_ph_tot}]}}
  cnt_is_booking_is_delivery_is_fav_is_ph_tot: {filter: {$or: [{<<: *is_booking}, {<<: *is_delivery}, {<<: *is_fav}, {<<: *is_ph_tot}]}}
  contacts_new:                            {filter: {$or: [{<<: *is_booking}, {<<: *is_delivery}, {<<: *is_ph_tot}]}}

metric.uniq:
  bt_clicks_grouped_new:                   {counter: bt_clicks_new,                   key: [item, user]}
  contacts_grouped_new:                    {counter: contacts_new,                    key: [item, user]}
  buyers_new:                              {counter: contacts_new,                    key: [user]}
  users_bt_click_daily_new:                {counter: cnt_is_booking_is_delivery_is_fav_is_ph_tot, key: [user]}

