metric.counter:
  is_contact_is_s_map_x_is_map_x_is_search: {filter: {*is_contact, $or: [{<<: [*is_s_map, *x_is_search]}, {*x_is_map}]}}
  is_iv_noguess_is_s_map_x_is_map_x_is_search: {filter: {*is_iv_noguess, $or: [{<<: [*is_s_map, *x_is_search]}, {*x_is_map}]}}
  is_iv_noguess_x_is_map:                  {filter: {<<: [*is_iv_noguess, *x_is_map]}}
  map_searches_to_btc_map:                 {obs: [map_searches_to_btc_map]}
  map_searches_to_iv_map:                  {obs: [map_searches_to_iv_map]}

metric.uniq:
  session_is_contact_is_s_map_x_is_map_x_is_search: {counter: is_contact_is_s_map_x_is_map_x_is_search, key: [session]}
  session_is_iv_noguess_is_s_map_x_is_map_x_is_search: {counter: is_iv_noguess_is_s_map_x_is_map_x_is_search, key: [session]}

metric.ratio:
  btc_from_map_per_map_search:             {num: buyer_target_clicks_from_map,    den: map_searches}
  btc_from_map_per_pin:                    {num: buyer_target_clicks_from_map,    den: pin_clicks}
  buyers_map_per_user_pin:                 {num: buyers_from_map,                 den: pin_clickers}
  contacts_from_map_per_map_search:        {num: contacts_from_map,               den: map_searches}
  contacts_from_map_per_pin:               {num: contacts_from_map,               den: pin_clicks}
  contacts_from_map_total_per_map_search:  {num: contacts_serp_map_total,         den: map_searches}
  fav_added_from_map_per_map_search:       {num: fav_added_from_map,              den: map_searches}
  fav_added_from_map_per_pin:              {num: fav_added_from_map,              den: pin_clicks}
  fav_from_map_total_per_map_search:       {num: fav_added_serp_map_total,        den: map_searches}
  item_views_from_map_per_map_search:      {num: item_views_from_map,             den: map_searches}
  item_views_from_map_per_pin:             {num: item_views_from_map,             den: pin_clicks}
  iv_from_map_total_per_map_search:        {num: item_views_from_map_total,       den: map_searches}
  map_area_per_map_search:                 {num: searches_map_area,               den: map_searches}
  map_btc_users_per_map_serchers:          {num: users_buyer_target_click_from_map, den: map_users}
  map_buyers_per_map_serchers:             {num: buyers_from_map,                 den: map_users}
  map_item_viewers_per_map_serchers:       {num: users_item_views_from_map,       den: map_users}
  map_nav_actions_per_btc_map:             {num: map_nav_actions,                 den: buyer_target_clicks_from_map}
  map_nav_actions_per_item_view_map:       {num: map_nav_actions,                 den: item_views_from_map}
  map_search_to_btc_map:                   {num: map_searches_to_btc_map,         den: users_buyer_target_click_from_map}
  map_search_to_iv_map:                    {num: map_searches_to_iv_map,          den: users_item_views_from_map}
  map_searches_per_search:                 {num: map_searches,                    den: searches}
  map_total_buyers_per_map_serchers:       {num: buyers_from_map_total,           den: map_users}
  sess_btc_map_per_sess_map:               {num: btc_sessions_from_map,           den: map_searches_sessions}
  sess_c_map_per_sess_map:                 {num: contact_sessions_from_map,       den: map_searches_sessions}
  sess_c_map_per_sess_pin:                 {num: contact_sessions_from_map,       den: pin_clicks_sessions}
  sess_c_map_total_per_sess_map:           {num: session_is_contact_is_s_map_x_is_map_x_is_search, den: map_searches_sessions}
  sess_iv_map_per_sess_map:                {num: iv_sessions_from_map,            den: map_searches_sessions}
  sess_iv_map_per_sess_pin:                {num: iv_sessions_from_map,            den: pin_clicks_sessions}
  sess_iv_map_total_per_sess_map:          {num: session_is_iv_noguess_is_s_map_x_is_map_x_is_search, den: map_searches_sessions}
  sess_map_area_per_sess_map:              {num: map_area_sessions,               den: map_searches_sessions}
  user_fav_map_total_per_user_map:         {num: user_fav_from_map_total,         den: map_users}
  user_iv_map_per_user_pin:                {num: users_item_views_from_map,       den: pin_clickers}
  user_iv_map_total_per_user_map:          {num: user_item_view_from_map_total,   den: map_users}

