metric.uniq:
  _is_ph_tot:                              {counter: phone_views_total,               key: []}

metric.ratio:
  ancalls_per_phone_view:                  {num: ancalls_any_type,                den: phone_views_total}
  ancalls_per_pv_btn:                      {num: ancalls_any_type,                den: phone_view_button_clicks}
  users_ancall_per_phone_view_user:        {num: users_ancalls_any_type,          den: _is_ph_tot}
  users_ancall_per_pv_btn_user:            {num: users_ancalls_any_type,          den: users_pv_button_clicks}

