observations_stats:
  t_confint:
    - {alpha: 0.05, alternative: '2s'}
  basic_stats:
  smart_stats:
    - {stat_func: mean, resampling: null}


compare_observations:
  t_test:
    - {null_value: 0, alternative: '>', stat_func: mean}
    - {null_value: 0, alternative: '<', stat_func: mean}
    - {null_value: 0, alternative: '2s', stat_func: mean}
  t_confint:
    - {alpha: 0.05, alternative: '2s'}
  mann_whitney_u_test:
    - {alternative: '>'}
    - {alternative: '<'}
    - {alternative: '2s'}
  basic_stats_pooled:
  smart_stats_pooled:
    - {comp_func: difference, stat_func: mean, resampling: null}
  smart_stats:
    - {comp_func: difference, stat_func: mean, resampling: null}
