observations_stats:
  smart_stats:
    - {stat_func: mean, resampling: null}


compare_observations:
  z_test:
    - {null_value: 0, alternative: '>', stat_func: mean}
    - {null_value: 0, alternative: '<', stat_func: mean}
    - {null_value: 0, alternative: '2s', stat_func: mean}
  smart_stats_pooled:
    - {stat_func: mean, resampling: null}
  smart_stats:
    - {comp_func: 'difference', stat_func: mean, resampling: null}
