breakdowns:
    total_breakdown:
        - {}

metrics_by_breakdowns:
    total_breakdown:
        all_main_pages
        head_main_pages
        users_all_main_page_daily
        users_head_main_page_daily
        users_vertical_main_page_daily
        shows_item_view_recblock
        shows_contact_recblock
        contacts_rec
        fav_added_rec
        buyer_target_clicks_rec
        item_views_rec
        item_views_rec_i2i
        item_views_rec_u2i
        contacts_rec_i2i
        contacts_rec_u2i
        fav_added_rec_i2i
        fav_added_rec_u2i
        buyer_target_clicks_rec_i2i
        buyer_target_clicks_rec_u2i
        contacts_rec_per_rec_block
        buyer_target_clicks_rec_per_rec_block
        contacts_rec_per_item_views_rec
        shows_item_view_recblock_per_recblock_shows
        users_item_view_rec_daily
        users_contact_rec_daily
        users_buyer_target_click_rec_daily
        users_contact_rec_i2i
        users_contact_rec_u2i
        users_item_view_rec_i2i
        users_item_view_rec_u2i
        users_item_views_rec_u2i_per_users_all_main_pages
        users_item_views_rec_i2i_per_users_item_views
        users_contacts_rec_u2i_per_users_all_main_pages
        users_contacts_rec_i2i_per_users_item_views
        users_contacts_rec_i2i_per_users_item_views_rec_i2i
        users_contacts_rec_u2i_per_users_item_views_rec_u2i
        item_views
        contacts
        phone_views_snippet
        phone_views
        phone_views_total
        favorites_added
        first_messages
        bt_clicks
        phone_views_per_item_view
        contacts_per_item_view
        users_active_daily
        users_item_view_daily
        buyers
        users_bt_click_daily
        buyers_per_users
        users_item_view_per_users
        users_bt_click_per_users
        mean_time_to_content_item_screen
        mean_time_to_content_serp_screen
        mean_time_to_content_main_screen
        searches_with_query
        searches_without_query
        searches
        searches_serp
        serp_empty
        serp_small
        searches_item_view_vas
        searches_item_view_serp
        item_views_vip
        item_views_premium
        item_views_push
        item_views_vas
        item_views_serp
        contacts_vip
        contacts_premium
        contacts_vas
        contacts_serp
        fav_added_vip
        fav_added_premium
        fav_added_serp
        buyer_target_clicks_premium
        buyer_target_clicks_push
        buyer_target_clicks_vas
        buyer_target_clicks_serp
        item_views_vip_per_search
        item_views_premium_per_search
        item_views_push_per_search
        item_views_serp_per_search
        contacts_vip_per_search
        contacts_premium_per_search
        contacts_push_per_search
        contacts_serp_per_search
        fav_added_vip_per_search
        fav_added_premium_per_search
        fav_added_push_per_search
        fav_added_vas_per_search
        buyer_target_clicks_vip_per_search
        buyer_target_clicks_premium_per_search
        buyer_target_clicks_push_per_search
        buyer_target_clicks_serp_per_search
        contacts_vip_per_item_views_vip
        contacts_premium_per_item_views_premium
        contacts_push_per_item_views_push
        contacts_serp_per_item_views_serp
        searches_item_view_serp_per_searches_serp
        users_search
        users_search_query
        users_item_view_serp_daily
        users_item_view_search_query
        users_contact_serp_daily
        users_buyer_target_click_serp_daily
        users_contact_search_query
        users_item_view_per_search
        users_contact_per_search
        users_contact_per_item_view_search
        users_item_view_per_search_query
        users_contact_per_search_query
        delivery_orders_created