searches_with_query:
  observation_template: single_event_count
  sql_bindings:
    source_event_name: search_with_query

searches_without_query:
  observation_template: single_event_count
  sql_bindings:
    source_event_name: search_without_query

item_views:
  observation_template: single_event_count
  sql_bindings:
    source_event_name: item_view

phone_views:
  observation_template: single_event_count
  sql_bindings:
    source_event_name: phone_view
