search_with_query:
  template: click_stream
  sql_bindings:
    event_types: 300
    filter_predicate: AND cs.searchquery_id IS NOT NULL

search_without_query:
  template: click_stream
  sql_bindings:
    event_types: 300
    filter_predicate: AND cs.searchquery_id IS NULL

item_view:
  template: click_stream
  sql_bindings:
    event_types: 301

phone_view:
  template: click_stream
  sql_bindings:
    event_types: 303

favorite_add:
  template: click_stream
  sql_bindings:
    event_types: 401, 2574

favorite_remove:
  template: click_stream
  sql_bindings:
    event_types: 402

favorites_list_view:
  template: click_stream
  sql_bindings:
    event_types: 400

saved_search_add:
  template: click_stream
  sql_bindings:
    event_types: 2071

saved_search_remove:
  template: click_stream
  sql_bindings:
    event_types: 2340

saved_searches_list_view:
  template: click_stream
  sql_bindings:
    event_types: 2341

forgot_password:
  template: click_stream
  sql_bindings:
    event_types: 2090

password_restore_request:
  template: click_stream
  sql_bindings:
    event_types: 212
    filter_predicate: AND cs.error_code IS NULL

password_restore_request_error:
  template: click_stream
  sql_bindings:
    event_types: 212
    filter_predicate: AND cs.error_code IS NOT NULL

password_restore:
  template: click_stream
  sql_bindings:
    event_types: 213
    filter_predicate: AND cs.error_code IS NULL

password_restore_error:
  template: click_stream
  sql_bindings:
    event_types: 213
    filter_predicate: AND cs.error_code IS NOT NULL

sign_in:
  template: click_stream
  sql_bindings:
    event_types: 210
    filter_predicate: AND cs.error_code IS NULL

sign_in_error:
  template: click_stream
  sql_bindings:
    event_types: 210
    filter_predicate: AND cs.error_code IS NOT NULL

first_message:
  template: click_stream
  sql_bindings:
    event_types: 856, 857

main_page:
  template: click_stream
  sql_bindings:
    event_types: 2572    

phone_view_anon_number:
  template: click_stream_item_anon_number
  sql_bindings:
    event_types: 303

autoteka_redir_from_item:
  template: click_stream
  sql_bindings:
    event_types: 2374
    filter_predicate: AND cs.apptype_id = 500010

autoteka_redir_from_about_report:
  template: click_stream
  sql_bindings:
    event_types: 2765
    filter_predicate: AND cs.apptype_id = 500010

public_profile:
  template: click_stream
  sql_bindings:
    event_types: 2016

phone_view_realty_suspicious_user_flag:
  template: click_stream_realty_suspicious_user_flag
  sql_bindings:
    event_types: 303
    
item_view_realty_suspicious_user_flag:
  template: click_stream_realty_suspicious_user_flag
  sql_bindings:
    event_types: 301

delivery_flow_begining:
  template: click_stream
  sql_bindings:
    event_types: 2013

delivery_order:
  template: delivery_orders

installment_card_views:
  template: click_stream
  sql_bindings:
    event_types: 2624
    filter_predicate: AND cs.is_delivery_active AND cs.subcategory_id = 41