search_with_query:
  template: click_stream
  sql_bindings:
    event_types: 300
    filter_predicate: AND cs.searchquery_id IS NOT NULL

search_without_query:
  template: click_stream
  sql_bindings:
    event_types: 300
    filter_predicate: AND cs.searchquery_id IS NULL

item_view:
  template: click_stream
  sql_bindings:
    event_types: 301

phone_view_item_right:
  template: click_stream
  sql_bindings:
    event_types: 303
    filter_predicate: AND (cs.phone_view_source = 'r' or cs.phone_view_source is null)

phone_view_item_top:
  template: click_stream
  sql_bindings:
    event_types: 303
    filter_predicate: AND cs.phone_view_source = 't'

phone_view_snippet:
  template: click_stream
  sql_bindings:
    event_types: 303
    filter_predicate: AND cs.phone_view_source = 's'
    
delivery_order_create:
  template: click_stream
  sql_bindings:
    event_types: 2015
    
phone_view_snippet_xlvas:
  template: click_stream
  sql_bindings:
    event_types: 303
    filter_predicate: AND cs.phone_view_source = 'xs'

favorite_add:
  template: click_stream
  sql_bindings:
    event_types: 401, 2574

favorite_remove:
  template: click_stream
  sql_bindings:
    event_types: 402

favorites_list_view:
  template: click_stream
  sql_bindings:
    event_types: 400

saved_search_add:
  template: click_stream
  sql_bindings:
    event_types: 2071

saved_search_remove:
  template: click_stream
  sql_bindings:
    event_types: 2340

saved_searches_list_view:
  template: click_stream
  sql_bindings:
    event_types: 2341

forgot_password:
  template: click_stream
  sql_bindings:
    event_types: 2090

password_restore_request:
  template: click_stream
  sql_bindings:
    event_types: 212
    filter_predicate: AND cs.error_code IS NULL

password_restore_request_error:
  template: click_stream
  sql_bindings:
    event_types: 212
    filter_predicate: AND cs.error_code IS NOT NULL

password_restore:
  template: click_stream
  sql_bindings:
    event_types: 213
    filter_predicate: AND cs.error_code IS NULL

password_restore_error:
  template: click_stream
  sql_bindings:
    event_types: 213
    filter_predicate: AND cs.error_code IS NOT NULL

sign_in:
  template: click_stream
  sql_bindings:
    event_types: 210
    filter_predicate: AND cs.error_code IS NULL

sign_in_error:
  template: click_stream
  sql_bindings:
    event_types: 210
    filter_predicate: AND cs.error_code IS NOT NULL

first_message:
  template: click_stream
  sql_bindings:
    event_types: 856, 857

head_main_page:
  template: click_stream
  sql_bindings:
    event_types: 2572
    
transport_main_page:
  template: click_stream
  sql_bindings:
    event_types: 2592 
    filter_predicate: AND cs.category_id = 12
    
re_main_page:
  template: click_stream
  sql_bindings:
    event_types: 2592 
    filter_predicate: AND cs.category_id = 39
    
services_main_page:
  template: click_stream
  sql_bindings:
    event_types: 2592 
    filter_predicate: AND cs.category_id = 250005

phone_view_anon_number:
  template: click_stream_item_anon_number
  sql_bindings:
    event_types: 303

autoteka_redir_from_item:
  template: click_stream
  sql_bindings:
    event_types: 2374
    filter_predicate: AND cs.apptype_id = 500010

autoteka_redir_from_about_report:
  template: click_stream
  sql_bindings:
    event_types: 2765
    filter_predicate: AND cs.apptype_id = 500010

public_profile:
  template: click_stream
  sql_bindings:
    event_types: 2016

phone_view_realty_suspicious_user_flag:
  template: click_stream_realty_suspicious_user_flag
  sql_bindings:
    event_types: 303
    
item_view_realty_suspicious_user_flag:
  template: click_stream_realty_suspicious_user_flag
  sql_bindings:
    event_types: 301

delivery_flow_begining:
  template: click_stream
  sql_bindings:
    event_types: 2013

delivery_order:
  template: delivery_orders

installment_card_view:
  template: click_stream
  sql_bindings:
    event_types: 2642
    filter_predicate: AND cs.is_delivery_active AND cs.subcategory_id = 41

item_add:
  template: click_stream
  sql_bindings:
    event_types: 310
    filter_predicate: AND cs.item_id is not null
    
item_add_start:
  template: click_stream
  sql_bindings:
    event_types: 310
    filter_predicate: AND cs.item_id is null AND cs.location_id is null AND cs.category_id is null AND cs.subcategory_id is null AND cs.vertical_id is null AND cs.logical_category_id is null
