default:
  - metric_date
  - participant_type
  - is_participant_new
  - is_human
  - is_logged_in
  - platform_id
  - user_segment
  - vertical_id
  - logical_category_id
  - category_id
  - subcategory_id
  - region_id


metrics_by_dimension:
  users_active_daily: [app_version]
  buyers_canonical: [price_group]

presets_by_dimension:
  sx_ss: [user_segment_market]
  sx_fullbase: [user_segment_market]
  big10: [is_asd,user_segment_market]
