default: [participant_type, 
          is_participant_new, 
          is_human, 
          is_authorized, 
          user_segment,
          vertical,
          log_category,
          category,
          sub_category,
          location,
          param1]


metrics_by_dimension:
  active_items_total: [city,app_version]
  users_item_allowed_total: [app_version]


pesets_by_dimension:
  sx_total: [city,region]
