default: [participant_type, 
          is_participant_new, 
          is_human, 
          is_authorized, 
          user_segment,
          vertical,
          log_category,
          category,
          sub_category,
          location]


metrics_by_dimension:
  users_active_daily: [app_version]
  buyers_canonical: [price_group]
  sx_ss: [user_segment_market]
  sx_fullbase: [user_segment_market]