default:
  - metric_date
  - participant_type
  - is_participant_new
  - is_human
  - is_logged_in
  - platform_id
  - is_asd
  - user_segment_market
  - user_segment
  - vertical_id
  - logical_category_id
  - category_id
  - subcategory_id
  - region_id


metrics_by_dimension:
  users_active_daily: [app_version]
  buyers_canonical: [price_group]

