default: [participant_type, 
          is_participant_new, 
          is_human, 
          is_authorized, 
          user_segment,
          vertical,
          logical_category,
          category,
          subcategory,
          region]


metrics_by_dimension:
  users_active_daily: [app_version]
  buyers_canonical: [price_group]

pesets_by_dimension:
  sx_ss: [user_segment_market]
  sx_fullbase: [user_segment_market]