by_metric:
  users_active_daily: [[app_version], [vertical, logical_category, region]]
  buyers_canonical: [[price_group], [category, subcategory, param1], [vertical, logical_category, region]]
  contacts_canonical: [[category, subcategory, param1], [vertical, logical_category, region]]
  active_items: [[category, subcategory, param1], [vertical, logical_category, region]]
  items_started_net: [[category, subcategory, param1], [vertical, logical_category, region]]
  users_active_items: [[category, subcategory, param1], [vertical, logical_category, region]]
  users_item_started: [[category, subcategory, param1], [vertical, logical_category, region]]
  sellers_with_contacts: [[category, subcategory, param1], [vertical, logical_category, region]]
  classified_amount_net_adj: [[category, subcategory, param1], [vertical, logical_category, region]]
  vas_amount_net_adj: [[category, subcategory, param1], [vertical, logical_category, region]]
  paid_contact_amount_net_adj: [[category, subcategory, param1], [vertical, logical_category, region]]
  lf_amount_net_adj: [[category, subcategory, param1], [vertical, logical_category, region]]
  lf_amount_net:
    - [is_logged_in, is_asd, vertical, logical_category, logical_param1, logical_param2, region, user_segment_market]
  items_reactivated_net:
    - [is_logged_in, is_asd, vertical, logical_category, logical_param1, logical_param2, region, user_segment_market]
  items_sold_onavito:
    - [is_logged_in, is_asd, vertical, logical_category, logical_param1, logical_param2, region, user_segment_market]
  items_sold_onavito_per_items_reactivated_net:
    - [is_logged_in, is_asd, vertical, logical_category, logical_param1, logical_param2, region, user_segment_market]
by_metric_list:
  app_errors: [[app_version]]
