by_metric:
  users_active_daily: [[app_version], [vertical, logical_category, region]]
  buyers_canonical: [[price_group], [category, subcategory, param1], [vertical, logical_category, logical_param1, logical_param2, region]]
  contacts_canonical: [[category, subcategory, param1], [vertical, logical_category, logical_param1, logical_param2, region]]
  active_items: [[category, subcategory, param1, param2], [vertical, logical_category, region, city]]
  items_started_net: [[category, subcategory, param1, param2], [vertical, logical_category, region, city]]
  users_active_items: [[category, subcategory, param1], [vertical, logical_category, region]]
  users_item_started: [[category, subcategory, param1], [vertical, logical_category, region]]
  sellers_with_contacts: [[category, subcategory, param1], [vertical, logical_category, region]]
  classified_amount_net_adj: [[category, subcategory, param1], [vertical, logical_category, region]]
  vas_amount_net_adj: [[category, subcategory, param1], [vertical, logical_category, region]]
  paid_contact_amount_net_adj: [[category, subcategory, param1], [vertical, logical_category, region]]
  lf_amount_net_adj: [[category, subcategory, param1], [vertical, logical_category, region]]
  lf_amount_net:
    - [is_logged_in, is_asd, vertical, logical_category, logical_param1, logical_param2, region, user_segment_market]
  items_reactivated_net:
    - [is_logged_in, is_asd, vertical, logical_category, logical_param1, logical_param2, region, city, user_segment_market]
  items_sold_onavito:
    - [is_logged_in, is_asd, vertical, logical_category, logical_param1, logical_param2, region, user_segment_market]
  items_sold_onavito_per_items_reactivated_net:
    - [is_logged_in, is_asd, vertical, logical_category, logical_param1, logical_param2, region, user_segment_market]
  returned_buyers:
    - [is_logged_in, is_asd, vertical, logical_category, logical_param1, logical_param2, region, user_segment_market]
  cnt_returned_buyers:
    - [is_logged_in, is_asd, vertical, logical_category, logical_param1, logical_param2, region, user_segment_market]
  item_views: [[is_logged_in, vertical, logical_category, region, city], [vertical, logical_category, logical_param1, logical_param2]]
  contacts: [[is_logged_in, vertical, logical_category, region, city], [vertical, logical_category, logical_param1, logical_param2]]
  
  # ---- временные метрики для теста(сравнить с метриками vas без приставки cfr_)
  vas_amount_net: [[vertical, logical_category, logical_param1, logical_param2, region, city, is_asd, user_segment_market]]
  vas_amount_net_x2_7: [[vertical, logical_category, logical_param1, logical_param2, region, city, is_asd, user_segment_market]]
  vas_amount_net_x5_1: [[vertical, logical_category, logical_param1, logical_param2, region, city, is_asd, user_segment_market]]
  vas_amount_net_x2_1: [[vertical, logical_category, logical_param1, logical_param2, region, city, is_asd, user_segment_market]]
  vas_amount_net_x10_1: [[vertical, logical_category, logical_param1, logical_param2, region, city, is_asd, user_segment_market]]
  vas_amount_net_x10_7: [[vertical, logical_category, logical_param1, logical_param2, region, city, is_asd, user_segment_market]]
  vas_amount_net_x5_7: [[vertical, logical_category, logical_param1, logical_param2, region, city, is_asd, user_segment_market]]
  # ---------------------------------------------------
by_metric_list:
  app_errors: [[app_version]]
