breakdowns:
    breakdown_total:
      - {}
    breakdown_vertical:
      - {vertical: [Transport]}
      - {vertical: [Realty]}
      - {vertical: [General]}
      - {vertical: [Jobs]}
      - {vertical: [Services]}
      - {vertical: [SpareParts]}
    breakdown_vertical_jobs:
      - {vertical: [Jobs]}
      - {vertical: [Jobs], logical_category: [Jobs.CVs]}
      - {vertical: [Jobs], logical_category: [Jobs.Vacancies]}
      - {vertical: [Jobs], logical_category: [Jobs.Undefined]}
    breakdown_vertical_general:
      - {vertical: [General]}
      - {vertical: [General], logical_category: [General.Animals]}
      - {vertical: [General], logical_category: [General.ChildrensGoods]}
      - {vertical: [General], logical_category: [General.ConstructionRenovation]}
      - {vertical: [General], logical_category: [General.Electronics]}
      - {vertical: [General], logical_category: [General.ForBusiness]}
      - {vertical: [General], logical_category: [General.ForHome]}
      - {vertical: [General], logical_category: [General.Hobby]}
      - {vertical: [General], logical_category: [General.PersonalBelongings]}

subscriptions:
  - owner: gvfandeev
    subscribers: [vleksin, dobelyakov]
    metrics:
      buyers:
        breakdowns:
          - is_human: ['false']

  - owner: igurov
    subscribers: []
    metrics:
      activated_listers:
        breakdowns:
          - {}

  - owner: pmpuryaev
    subscribers: []
    metrics:
      domofond_amount_net_adj:
        breakdowns:
          - {}

  - owner: ryabudylin
    subscribers: []
    metrics:
      autoteka_amount_net_adj:
        breakdowns:
          - {}

  - owner: aimalinskiy
    subscribers: ['#messenger_green_light']
    metrics_by_breakdowns:
      breakdown_total:
        - first_messages
        - first_response_messages
        - items_sold_onavito_from_messenger
        - messenger_active_chats
        - messenger_dau
        - messenger_spam_ratio
        - messenger_visitors
        - total_messages
        - users_first_response_messages
        - users_item_sold_onavito_from_messenger
        - write_button_clicks
        - first_mess_per_write_button_clicks
        - item_views_from_messenger
        - items_closed_from_messenger
        - messenger_geo_messages
        - messenger_spam_blocks
        - phone_views_in_chat
        - users_item_closed_from_messenger
        - users_phone_views_in_chat
        - users_write_button_clicks
        - write_button_clicks_per_item_views
        - chats_deleted
        - messenger_auto_messages
        - messenger_image_messages
        - messenger_item_messages
        - messenger_users_blocked
        - users_chat_open_errors
        - messages_view_events
        - user_messages_view_events

  - owner: megoncharov
    subscribers: [avshoyko]
    metrics_by_breakdowns:
      breakdown_total:
        - daily_active_authorized_users
        - user_enter_cr
        - search_items_ratings_coverage

  - owner: gvfandeev
    subscribers: ['#general-green-light']
    metrics_by_breakdowns:
      breakdown_vertical_general:
        - buyers_canonical

  - owner: aaeremina
    subscribers: ['#general-green-light']
    metrics_by_breakdowns:
      breakdown_vertical_general:
        - classified_amount_net_adj

  - owner: advelnikovskaya
    subscribers: ['#general-green-light']
    metrics_by_breakdowns:
      breakdown_vertical_general:
        - items_started_net
        - active_items
        - active_listers

  - owner: meperetrukhina
    subscribers: ['#general-green-light']
    metrics_by_breakdowns:
      breakdown_vertical_general:
        - items_sold_onavito

  - owner: gvfandeev
    subscribers: [satimofeev]
    metrics_config:
      bx: [breakdown_total]

  - owner: gvfandeev
    subscribers: [asprimak]
    metrics_config:
      geo: [breakdown_total]

  - owner: aaeremina
    subscribers: []
    metrics_by_breakdowns:
      breakdown_total:
        - classified_amount_net_adj
        - classified_arpu_net_adj
        - classified_paying_users_ratio
        - classified_price_net_adj
        - classified_transactions
        - classified_transactions_per_user
        - classified_users
        - other_projects_amount_net_adj

  - owner: aaeremina
    subscribers: []
    metrics_by_breakdowns:
      breakdown_total:
        - classified_amount_net_adj
        - classified_arpu_net_adj
        - classified_paying_users_ratio
        - classified_price_net_adj
        - classified_transactions
        - classified_transactions_per_user
        - classified_users
        - other_projects_amount_net_adj

  - owner: easaltykova
    subscribers: [easaltykova]
    metrics_by_breakdowns:
      breakdown_vertical:
        - lf_revenue
        - lf_revenue_net
        - listings_number
        - lf_revenue_single
        - lf_revenue_single_net
        - lf_revenue_package
        - lf_revenue_package_net
        - lf_revenue_package_burned
        - lf_revenue_package_burned_net
        - tariff_base_revenue
        - tariff_base_revenue_net
        - tariff_pro_revenue
        - tariff_pro_revenue_net
        - subs_transactions_per_user

  - owner: meperetrukhina
    subscribers: [eiivkina, mrkhabibrakhmanov]
    metrics_config:
      sx_ss: [breakdown_total]
      
  - owner: advelnikovskaya
    subscribers: [evtolstykh]
    metrics_config:
      sx_fullbase: [breakdown_total]

  - owner: dasergeev
    subscribers: [almirskoy]
    metrics_config:
      delivery: [breakdown_total]

  - owner: apraslov
    subscribers: [easaltykova]
    metrics_config:
      mnz_vas: [breakdown_total]

  - owner: epchumachenko
    subscribers: [makamenshchikov, vnrubtsov, vskopytov, vleksin, spopova]
    metrics_config:
      rec: [breakdown_total]
  
  - owner: epchumachenko
    subscribers: [epchumachenko, makamenshchikov, vnrubtsov, vskopytov, vleksin, spopova]
    metrics_config:
      rec: [breakdown_vertical]
