searches_with_query:
  observations: [searches_with_query]

searches_without_query:
  observations: [searches_without_query]

item_views:
  observations: [item_views]

phone_views:
  observations: [phone_views]
