searches_with_query:
  observations: [searches_with_query]
  template: observations_sum

searches_without_query:
  observations: [searches_without_query]
  template: observations_sum

item_views:
  observations: [item_views]
  template: observations_sum

phone_views:
  observations: [phone_views]
  template: observations_sum

favorites_added:
  observations: [favorites_added]
  template: observations_sum

favorites_removed:
  observations: [favorites_removed]
  template: observations_sum

favorites_list_views:
  observations: [favorites_list_views]
  template: observations_sum

saved_searches_added:
  observations: [saved_searches_added]
  template: observations_sum

saved_searches_removed:
  observations: [saved_searches_removed]
  template: observations_sum

saved_searches_list_views:
  observations: [saved_searches_list_views]
  template: observations_sum

forgot_password_count:
  observations: [forgot_password_count]
  template: observations_sum

password_restore_requests:
  observations: [password_restore_requests]
  template: observations_sum

password_restore_request_proportion:
  observations: [password_restore_requests]
  template: observations_proportion
  description: "1 если хотя бы один запрос на восстановление пароля, иначе 0"
  params: params_proportion

password_restore_request_errors:
  observations: [password_restore_request_errors]
  template: observations_sum

password_restore_count:
  observations: [password_restore_count]
  template: observations_sum

password_restore_proportion:
  observations: [password_restore_count]
  template: observations_proportion
  params: params_proportion

password_restore_errors:
  observations: [password_restore_errors]
  template: observations_sum

sign_in_count:
  observations: [sign_in_count] 
  template: observations_sum

sign_in_proportion:
  observations: [sign_in_count]
  template: observations_proportion
  params: params_proportion

sign_in_errors:
  observations: [sign_in_errors] 
  template: observations_sum

first_messages:
  observations: [first_messages]
  template: observations_sum

daily_buyers:
  observations: [phone_views, first_messages]
  template: observations_proportion_daily
  
advertisement_page_views:
  observations: [item_views, main_pages, searches_with_query, searches_without_query]
  template: observations_sum 
  
contacts:
  observations: [phone_views, first_messages]
  template: observations_sum 

phone_views_anon_number:
  observations: [phone_views_anon_number]
  template: observations_sum

autoteka_redirs:
  observations: [autoteka_redirs_from_item, autoteka_redirs_from_about_report]
  template: observations_sum
  description: "переход в автотеку с карточки объявления или из раздела Узнать больше об отчёте"

public_profiles:
  observations: [public_profiles]
  template: observations_sum

phone_views_realty_suspicious_user_flag:
  observations: [phone_views_realty_suspicious_user_flag]
  template: observations_sum

item_views_realty_suspicious_user_flag:
  observations: [item_views_realty_suspicious_user_flag]
  template: observations_sum