- owners: [gvfandeev]
  subscribers: [satimofeev]
  metrics:
    buyers:
      breakdowns:
        - {}
 
- owners: [gvfandeev]
  subscribers: [vleksin, dobelyakov]
  metrics:
    buyers:
      breakdown:
      - is_human: ['false']
      
​
- owners: [meperetrukhina]
  subscribers: [eiivkina, mrkhabibrakhmanov]
  metrics_config:
    sx: [sx_breakdowns_services]