breakdowns:
    breakdown_total:
      - {}
    breakdown_vertical:
      - {vertical: [Transport]}
      - {vertical: [Realty]}
      - {vertical: [General]}
      - {vertical: [Jobs]}
      - {vertical: [Services]}
      - {vertical: [SpareParts]}
    breakdown_vertical_jobs:
      - {vertical: [Jobs]}
      - {vertical: [Jobs], logical_category: [Jobs.CVs]}
      - {vertical: [Jobs], logical_category: [Jobs.Vacancies]}
      - {vertical: [Jobs], logical_category: [Jobs.Undefined]}
    breakdown_vertical_general:
      - {vertical: [General]}
      - {vertical: [SpareParts]}
      - {vertical: [General], logical_category: [General.Animals]}
      - {vertical: [General], logical_category: [General.GoodsForPets]}
      - {vertical: [General], logical_category: [General.GoodsForChildren]}
      - {vertical: [General], logical_category: [General.ConstructionRenovation]}
      - {vertical: [General], logical_category: [General.Electronics]}
      - {vertical: [General], logical_category: [General.Business]}
      - {vertical: [General], logical_category: [General.GoodsForBusiness]}
      - {vertical: [General], logical_category: [General.HomeAndGarden]}
      - {vertical: [General], logical_category: [General.Furniture]}
      - {vertical: [General], logical_category: [General.Hobby]}
      - {vertical: [General], logical_category: [General.Sports]}
      - {vertical: [General], logical_category: [General.Food]}
      - {vertical: [General], logical_category: [General.HealthAndBeauty]}
      - {vertical: [General], logical_category: [General.Fashion]}
      - {vertical: [General], logical_category: [General.Undefined]}
    breakdown_vertical_realty:
      - {vertical: [Realty]}
      - {vertical: [Realty], logical_category: [Realty.Commercial]}
      - {vertical: [Realty], logical_category: [Realty.LongRent]}
      - {vertical: [Realty], logical_category: [Realty.NewDevelopments]}
      - {vertical: [Realty], logical_category: [Realty.Other]}
      - {vertical: [Realty], logical_category: [Realty.SecondarySell]}
      - {vertical: [Realty], logical_category: [Realty.ShortRent]}
      - {vertical: [Realty], logical_category: [Realty.Suburban]}
      - {vertical: [Realty], logical_category: [Realty.Undefined]}
    is_cookie_new:
      - {}
      - {is_cookie_new: ['true']}
      - {is_cookie_new: ['false']}

subscriptions:
  - owner: gvfandeev
    subscribers: [epchumachenko]
    metrics:
      buyers:
        breakdowns:
          - is_human: ['false']

  - subscribers: ['#realty-metrics-alerts']
    metrics_by_breakdowns:
      breakdown_vertical_realty:
        - active_items
        - active_listers
        - buyers
        - contacts
        - classified_amount_net_adj
        - lf_amount_net_adj
        - vas_amount_net_adj
        - subs_amount_net_adj
        - cpa_amount_net_adj
        - items_reactivated_net
        - items_reactivated_net_conversion
        - items_started_net
        - items_started_net_conversion
        - item_views
        - searches
        - daily_active_users
        - calls
        - c_developer
        - contacts_cpa

  - owner: ryabudylin
    subscribers: []
    metrics:
      autoteka_amount_net_adj:
        breakdowns:
          - {}

  - owner: msyablochnikova
    subscribers: ['#messenger_green_light']
    metrics_by_breakdowns:
      breakdown_total:
        - first_messages
        - first_response_messages
        - items_sold_onavito_from_messenger
        - messenger_active_chats
        - messenger_dau
        - messenger_spam_ratio
        - messenger_visitors
        - total_messages
        - users_first_response_messages
        - users_item_sold_onavito_from_messenger
        - write_button_clicks
        - first_mess_per_write_button_clicks
        - item_views_from_messenger
        - items_closed_from_messenger
        - messenger_geo_messages
        - messenger_spam_blocks
        - phone_views_in_chat
        - users_item_closed_from_messenger
        - users_phone_views_in_chat
        - users_write_button_clicks
        - write_button_clicks_per_item_views
        - chats_deleted
        - messenger_auto_messages
        - messenger_image_messages
        - messenger_item_messages
        - messenger_users_blocked
        - users_chat_open_errors

  - owner: inzhuchkov
    subscribers: [mipolyanskaya, aashabalina]
    metrics_by_breakdowns:
      breakdown_total:
        - daily_active_authorized_users
        - user_enter_cr
        - user_enter_attempt
        - user_enter_start
        - search_items_ratings_coverage

  - owner: aaazimova
    subscribers: ['#general-green-light']
    metrics_by_breakdowns:
      breakdown_vertical_general:
        - classified_amount_net_adj

  - owner: advelnikovskaya
    subscribers: ['#general-green-light']
    metrics_by_breakdowns:
      breakdown_vertical_general:
        - items_started_net
        - active_items
        - active_listers
        - items_reactivated_net

  - owner: avdenisova
    subscribers: ['#general-green-light']
    metrics_by_breakdowns:
      breakdown_vertical_general:
        - items_sold_onavito

  - owner: satimofeev
    subscribers: [satimofeev, gvfandeev, epchumachenko, asprimak, '#bx-metrics-alarms']
    metrics_config:
      bx: [breakdown_total]

  - owner: asprimak
    subscribers: [asprimak, gvfandeev,'#bx-metrics-alarms']
    metrics_config:
      geo: [breakdown_total]
      geo_map: [breakdown_total]

  - owner: gvfandeev
    subscribers: [gvfandeev,satimofeev,epchumachenko,'#bx-metrics-alarms']
    metrics_config:
      app_errors: [breakdown_total]
      web_errors: [breakdown_total]

  - owner: gvfandeev
    subscribers: [asprimak, '#laas-metrics-alarms']
    metrics_config:
      geo_laas_subs: [breakdown_total]
      geo_coords_subs: [breakdown_total]

  - subscribers: ['#geo-alerts']
    metrics_config:
      geo_subs: [breakdown_total]

  - owner: aaazimova
    subscribers: []
    metrics_by_breakdowns:
      breakdown_total:
        - classified_amount_net_adj
        - classified_arpu_net_adj
        - classified_price_net_adj
        - classified_transactions
        - classified_users
        - other_projects_amount_net_adj

  - owner: aaazimova
    subscribers: []
    metrics_by_breakdowns:
      breakdown_total:
        - classified_amount_net_adj
        - classified_arpu_net_adj
        - classified_price_net_adj
        - classified_transactions
        - classified_users
        - other_projects_amount_net_adj

  - owner: easaltykova
    subscribers: [easaltykova, eibesedin, ngkokareva ]
    metrics_by_breakdowns:
      breakdown_vertical:
        - lf_revenue
        - lf_revenue_net
        - lf_activations
        - lf_users_count
        - single_listing_revenue
        - single_listing_activations
        - single_listing_users
        - tariff_base_revenue
        - tariff_pro_revenue
        - tariff_payin_amount
        - tariff_return_amount
        - tariff_payin_users
        - lf_amount_net_adj
        - lf_paying_users_ratio
        - lf_price_net_adj
        - lf_transactions
        - lf_transactions_per_user
        - lf_users
        - subs_amount_net_adj
        - subs_w_extensions_amount_net_adj
        - subs_w_extensions_transactions
        - subs_transactions
        - lf_arpu_net_adj
        - subs_w_extensions_arpu_net_adj

  - owner: avdenisova
    subscribers: [avdenisova, advelnikovskaya]
    metrics_config:
      sx_ss: [breakdown_total]

  - owner: advelnikovskaya
    subscribers: [avdenisova]
    metrics_config:
      sx_fullbase: [breakdown_total]

  - owner: dasergeev
    subscribers: ['#general-green-light']
    metrics_config:
      delivery: [breakdown_total]

  - owner: eibesedin
    subscribers: [vigodunova, arostrovskiy]
    metrics_config:
      mnz_vas: [breakdown_total]

  - owner: apraslov
    subscribers: [eaodintsova]
    metrics_by_breakdowns:
      breakdown_total:
        - advertisement_rpm_net_adj
        - advertisement_amount_net_adj
    metrics_config:
      ads: [breakdown_total]

  - owner: epchumachenko
    subscribers: [makamenshchikov, vskopytov, spopova]
    metrics_config:
      rec: [breakdown_total]

  - owner: epchumachenko
    subscribers: [epchumachenko, makamenshchikov, vskopytov, spopova]
    metrics_config:
      rec: [breakdown_vertical]

  - owner: epchumachenko
    metrics_by_breakdowns:
      breakdown_total:
        - not_found_errors
        - user_not_found_errors

  - owner: tyusipov
    subscribers: ['#perf-ab-monitoring']
    metrics_by_breakdowns:
      breakdown_total:
        - draw_session_duration
        - draw_session_percent_p25
        - draw_session_percent_p50
        - draw_session_percent_p75
        - draw_session_percent_p95
        - session_duration
        - session_percent_p25
        - session_percent_p50
        - session_percent_p75
        - session_percent_p95

  - owner: inzhuchkov
    subscribers: [inzhuchkov]
    metrics_by_breakdowns:
      breakdown_total:
        - sellers_with_rating

  - owner: iabalan
    subscribers: [iabalan]
    metrics_by_breakdowns:
      breakdown_total:
        - traffic_sessions

  - owner: maosipova
    subscribers: [maosipova]
    metrics_by_breakdowns:
      breakdown_total:
        - users_calltracking_active

  - owner: inzhuchkov
    subscribers: [inzhuchkov]
    metrics_by_breakdowns:
      breakdown_total:
        - active_sellers_with_fs_subscribers

  - owner: vvzimina
    subscribers: [vvzimina]
    metrics_by_breakdowns:
      breakdown_total:
        - support_chats_created
        - support_total_flow
        - support_contacters
        - support_email_wizard_tickets_created
        - support_helpcenter_sessions
        - support_callcenter_calls

  - owner: igurov
    subscribers: [igurov]
    metrics_by_breakdowns:
      breakdown_total:
        - image_draw_appstart_exceptions_percent

  - owner: abkrasnikov
    subscribers: [abkrasnikov]
    metrics_by_breakdowns:
      breakdown_total:
        - express_cv_allowed_conversion

  - owner: dvpimenova
    subscribers: [dvpimenova]
    metrics_by_breakdowns:
      breakdown_total:
        - search_suggest_clicks

  - owner: maosipova
    subscribers: [maosipova]
    metrics_by_breakdowns:
      breakdown_total:
        - anonnumber_long_talkers

  - owner: igurov
    subscribers: [igurov]
    metrics_by_breakdowns:
      breakdown_total:
        - total_memory_warnings_users

  - owner: dyurogova
    subscribers: [dyurogova]
    metrics_by_breakdowns:
      breakdown_total:
        - app_pushes_open_per_push_to_receiver

  - owner: satimofeev
    subscribers: [almirskoy, '#general-green-light']
    metrics_by_breakdowns:
      breakdown_total:
        - buyers
        - buyers_canonical
        - bt_clicks
        - buyer_target_clicks_serp
        - buyer_target_clicks_rec
        - item_views
        - item_views_serp
        - item_views_rec
        - contacts
        - contacts_serp
        - contacts_rec
        - delivery_click_mp
        - delivery_item_view_mp
        - delivery_widget_mp
        - delivery_click_mp
        - delivery_contact_mp
        - new_buyers
      breakdown_vertical_general:
        - buyers
        - bt_clicks
        - buyer_target_clicks_serp
        - buyer_target_clicks_rec
        - item_views
        - item_views_serp
        - item_views_rec
        - contacts
        - contacts_serp
        - contacts_rec
        - delivery_click_mp
        - delivery_item_view_mp
        - delivery_widget_mp
        - delivery_click_mp
        - delivery_contact_mp
        - new_buyers

  - owner: mdavydov
    subscribers: [mdavydov]
    metrics_by_breakdowns:
      breakdown_total:
        - main_payment_methods_share

  - owner: dlenkov
    subscribers: ['#bi-and-dwh']
    metrics_by_breakdowns:
      is_cookie_new: [daily_active_users]

  - owner: satimofeev
    subscribers: ['#job-green-light']
    metrics_by_breakdowns:
      breakdown_vertical_jobs:
        - buyers_canonical
        - bt_clicks
        - buyer_target_clicks_serp
        - buyer_target_clicks_rec
        - contacts
        - contacts_rec
        - contacts_serp
        - item_views
        - item_views_rec
        - item_views_serp
        - phone_views
        - ad_clicks
        - favorites_added

  - owner: satimofeev
    subscribers: ['#job-green-light']
    metrics_by_breakdowns:
      breakdown_vertical_jobs:
        - searches
        - serp_empty

  - owner: msyablochnikova
    subscribers: ['#job-green-light']
    metrics_by_breakdowns:
      breakdown_vertical_jobs:
        - first_messages

  - owner: aaazimova
    subscribers: ['#job-green-light', abkrasnikov]
    metrics_by_breakdowns:
      breakdown_vertical_jobs:
        - classified_amount_net_adj
        - classified_arpu_net_adj
        - classified_price_net_adj
        - classified_transactions
        - classified_users
        - other_projects_amount_net_adj

  - owner: easaltykova
    subscribers: ['#job-green-light', abkrasnikov]
    metrics_by_breakdowns:
      breakdown_vertical_jobs:
        - lf_revenue_net
        - tariff_base_revenue
        - tariff_pro_revenue

  - owner: advelnikovskaya
    subscribers: ['#job-green-light', abkrasnikov]
    metrics_by_breakdowns:
      breakdown_vertical_jobs:
        - items_started_net
        - items_added_per_items_add_started
        - items_blocked_rejected
        - items_blocked
        - items_rejected
        - active_items
        - active_listers
        - item_edits
        - items_sold_onavito
        - items_closed_by_user
        - items_sold_another_reason
        - items_sold_notonavito

  - owner: abkrasnikov
    subscribers: ['#job-green-light', abkrasnikov]
    metrics_by_breakdowns:
      breakdown_vertical_jobs:
        - paid_contact_amount_net_adj

  - owner: eibesedin
    subscribers: ['#job-green-light', abkrasnikov]
    metrics_by_breakdowns:
      breakdown_vertical_jobs:
        - vas_amount_net
        - vas_amount_net_visual
        - vas_amount_net_performance
        - vas_transactions
        - vas_transactions_mnz_visual
        - vas_transactions_mnz_performance

  - owner: vvbadlo956
    subscribers: ['#appcalls-metrics-alerts']
    metrics_by_breakdowns:
      breakdown_total:
      ### buyers
        - appcall_show_buttons
        - appcall_click_inapp
        - appcall_click_phone
        - appcall_click_inapp_or_phone
        - appcall_bx_outgoing_direct
        - appcall_bx_outgoing_direct_answered
        - appcall_bx_outgoing_direct_success
        - appcall_bx_outgoing_callback
        - appcall_bx_outgoing_callback_answered
        - appcall_bx_outgoing_callback_success
        - appcall_bx_incoming
        - appcall_bx_incoming_answered
        - appcall_bx_incoming_success
        - appcall_bx_outgoing_direct_answered_ratio
        - appcall_bx_outgoing_direct_success_ratio
        - appcall_bx_outgoing_direct_success_answered_ratio
        - appcall_click_inapp_ratio
        - appcall_click_phone_ratio
        - appcall_click_inapp_or_phone_ratio
        - appcall_click_inapp_proportion
        - appcall_click_phone_proportion
      ### sellers
        - appcall_sx_outgoing
        - appcall_sx_outgoing_answered
        - appcall_sx_outgoing_success
        - appcall_sx_incoming_callback
        - appcall_sx_incoming_callback_ringing
        - appcall_sx_incoming_callback_answered
        - appcall_sx_incoming_callback_success
        - appcall_sx_incoming_direct
        - appcall_sx_incoming_direct_ringing
        - appcall_sx_incoming_direct_answered
        - appcall_sx_incoming_direct_success
        - appcall_sx_incoming_direct_mic_granted
        - appcall_sx_incoming_direct_mic_checked
        - appcall_item_add_iac_popup_show
        - appcall_item_add_iac_popup_accepted
        - appcall_item_add_iac_popup_accepted_ratio
        - appcall_sx_incoming_direct_initiated_ratio
        - appcall_sx_incoming_direct_ringing_ratio
        - appcall_sx_incoming_direct_answered_ratio
        - appcall_sx_incoming_direct_success_ratio
        - appcall_sx_incoming_direct_initiated_ringing_ratio
        - appcall_sx_incoming_direct_ringing_answered_ratio
        - appcall_sx_incoming_direct_answered_success_ratio
        - appcall_sx_incoming_direct_mic_granted_ratio

  - owner: avshoyko
    subscribers: [avshoyko, svkokanova, '#rar-metrics-alerts']
    metrics_by_breakdowns:
      breakdown_total:
        - reviews_added
        - users_reviews_added
        - created_reviews_list_open
        - user_created_reviews_list_open
        - received_reviews_list_open
        - user_received_reviews_list_open
        - review_add_open_page
        - user_review_add_open_page
        - review_delete
        - user_review_delete
        - reviews_list_open
        - user_reviews_list_open
        - sellers_with_rating_1
        - sellers_with_rating_2
        - sellers_with_rating_3
        - sellers_with_rating_4
        - sellers_with_rating_5
        - items_with_rating
        - buyers_on_rating_1
        - buyers_on_rating_2
        - buyers_on_rating_3
        - buyers_on_rating_4
        - buyers_on_rating_5
        - item_views_on_rating_1
        - item_views_on_rating_2
        - item_views_on_rating_3
        - item_views_on_rating_4
        - item_views_on_rating_5
        - item_views_on_rating
        - contacts_on_rating_1
        - contacts_on_rating_2
        - contacts_on_rating_3
        - contacts_on_rating_4
        - contacts_on_rating_5
        - contacts_on_rating
        - item_views_on_rating_share
        - contacts_on_rating_share
        - contacts_history_open_in_ratings
        - reviews_avg_score
        - contacts_per_item_view_on_rating_1
        - contacts_per_item_view_on_rating_2
        - contacts_per_item_view_on_rating_3
        - contacts_per_item_view_on_rating_4
        - contacts_per_item_view_on_rating_5
        - contacts_with_review_list_view
        - contacts_per_item_view_on_rating
        - contacts_with_review_list_view_per_contacts
        
  - owner: aashakirova
    subscribers: [aashakirova, '#cpa-metrics-alarms']
    metrics_by_breakdowns:
      breakdown_vertical:
        - cpa_amount_net_adj
        - cpa_transactions
        - cpa_users
        - buyer_target_clicks_cpa
        - item_views_cpa
        - contacts_cpa
