searches_with_query:
  events: [search_with_query]
  template: single_event_count

searches_without_query:
  events: [search_without_query]
  template: single_event_count

item_views:
  events: [item_view]
  template: single_event_count

phone_views:
  events: [phone_view]
  template: single_event_count
