searches_with_query:
  events: [search_with_query]
  template: single_event_count

searches_without_query:
  events: [search_without_query]
  template: single_event_count

item_views:
  events: [item_view]
  template: single_event_count

phone_views_item_right:
  events: [phone_view_item_right]
  template: single_event_count

phone_views_item_top:
  events: [phone_view_item_top]
  template: single_event_count

phone_views_snippet:
  events: [phone_view_snippet]
  template: single_event_count
  
phone_views_snippet_xlvas:
  events: [phone_view_snippet_xlvas]
  template: single_event_count
  
favorites_added:
  events: [favorite_add]
  template: single_event_count

favorites_removed:
  events: [favorite_remove]
  template: single_event_count

favorites_list_views:
  events: [favorites_list_view]
  template: single_event_count

saved_searches_added:
  events: [saved_search_add]
  template: single_event_count

saved_searches_removed:
  events: [saved_search_remove]
  template: single_event_count

saved_searches_list_views:
  events: [saved_searches_list_view]
  template: single_event_count

forgot_password_count:
  events: [forgot_password]
  template: single_event_count

password_restore_requests:
  events: [password_restore_request]
  template: single_event_count

password_restore_request_errors:
  events: [password_restore_request_error]
  template: single_event_count

password_restore_count:
  events: [password_restore]
  template: single_event_count

password_restore_errors:
  events: [password_restore_error]
  template: single_event_count

sign_in_count:
  events: [sign_in] 
  template: single_event_count

sign_in_errors:
  events: [sign_in_error] 
  template: single_event_count

first_messages:
  events: [first_message]
  template: single_event_count
  
head_main_pages:
  events: [head_main_page]
  template: single_event_count  
  
transport_main_pages:
  events: [transport_main_page]
  template: single_event_count  
  
re_main_pages:
  events: [re_main_page]
  template: single_event_count  
  
services_main_pages:
  events: [services_main_page]
  template: single_event_count  

phone_views_anon_number:
  events: [phone_view_anon_number]
  template: single_event_count

autoteka_redirs_from_item:
  events: [autoteka_redir_from_item]
  template: single_event_count

autoteka_redirs_from_about_report:
  events: [autoteka_redir_from_about_report]
  template: single_event_count

public_profiles:
  events: [public_profile]
  template: single_event_count

phone_views_realty_suspicious_user_flag:
  events: [phone_view_realty_suspicious_user_flag]
  template: single_event_count
  
item_views_realty_suspicious_user_flag:
  events: [item_view_realty_suspicious_user_flag]
  template: single_event_count

contacts_public_profile:
  template: tns_public_profile
  
public_profiles_unique:
  template: tns_public_profile

public_profile_paginations:
  template: tns_public_profile

public_profile_closed_items_tabs:
  template: tns_public_profile

public_profile_closed_items_paginations:
  template: tns_public_profile

delivery_flow_beginings:
  events: [delivery_flow_begining]
  template: single_event_count

delivery_orders:
  events: [delivery_order]
  template: single_event_count
  
searches_serp:
  template: search_stream

recblock_shows:
  template: search_stream

sum_click_min_position:
  template: search_stream

sum_click_max_position:
  template: search_stream

searches_item_view_vip:
  template: search_stream

searches_item_view_premium:
  template: search_stream

searches_item_view_push:
  template: search_stream

searches_item_view_vas:
  template: search_stream

searches_item_view_serp:
  template: search_stream

shows_item_view_recblock:
  template: search_stream

searches_contact_vip:
  template: search_stream

searches_contact_premium:
  template: search_stream

searches_contact_push:
  template: search_stream

searches_contact_vas:
  template: search_stream

searches_contact_serp:
  template: search_stream

shows_contact_recblock:
  template: search_stream

item_views_vip:
  template: search_stream

item_views_premium:
  template: search_stream

item_views_push:
  template: search_stream

item_views_vas:
  template: search_stream

item_views_serp:
  template: search_stream

item_views_rec:
  template: search_stream

contacts_vip:
  template: search_stream

contacts_premium:
  template: search_stream

contacts_push:
  template: search_stream

contacts_vas:
  template: search_stream

contacts_serp:
  template: search_stream

contacts_rec:
  template: search_stream

fav_added_vip:
  template: search_stream

fav_added_premium:
  template: search_stream

fav_added_push:
  template: search_stream

fav_added_vas:
  template: search_stream

fav_added_serp:
  template: search_stream

fav_added_rec:
  template: search_stream

buyer_target_clicks_vip:
  template: search_stream

buyer_target_clicks_premium:
  template: search_stream

buyer_target_clicks_push:
  template: search_stream

buyer_target_clicks_vas:
  template: search_stream

buyer_target_clicks_serp:
  template: search_stream

buyer_target_clicks_rec:
  template: search_stream

installment_card_views:
  events: [installment_card_view]
  template: single_event_count

items_added:
  events: [item_add]
  template: single_event_count
  
items_add_started:
  events: [item_add_start]
  template: single_event_count

serp_empty:
  template: search_stream
  
serp_small:
  template: search_stream

pages_listing_type:
  template: listing_activation_flow

pages_payment_method:
  template: listing_activation_flow

pages_success_payment:
  template: listing_activation_flow

listings_single_paid:
  template: paid_single_listings_activations