searches_with_query:
  events: [search_with_query]
  template: single_event_count
  sql_bindings:
    source_event_name: search_with_query

searches_without_query:
  events: [search_without_query]
  template: single_event_count
  sql_bindings:
    source_event_name: search_without_query

item_views:
  events: [item_view]
  template: single_event_count
  sql_bindings:
    source_event_name: item_view

phone_views:
  events: [phone_view]
  template: single_event_count
  sql_bindings:
    source_event_name: phone_view
