searches_with_query:
  events: [search_with_query]
  template: single_event_count

searches_without_query:
  events: [search_without_query]
  template: single_event_count

item_views:
  events: [item_view]
  template: single_event_count

phone_views:
  events: [phone_view]
  template: single_event_count

favorites_added:
  events: [favorite_add]
  template: single_event_count

favorites_removed:
  events: [favorite_remove]
  template: single_event_count

favorites_list_views:
  events: [favorites_list_view]
  template: single_event_count

saved_searches_added:
  events: [saved_search_add]
  template: single_event_count

saved_searches_removed:
  events: [saved_search_remove]
  template: single_event_count

saved_searches_list_views:
  events: [saved_searches_list_view]
  template: single_event_count
