observations_stats:
  proportion_confint:
    - {alpha: 0.05, alternative: '2s'}
  basic_stats:


compare_observations:
  z_test:
    - {null_value: 0, alternative: '>', comp_func: difference}
    - {null_value: 0, alternative: '<', comp_func: difference}
    - {null_value: 0, alternative: '2s', comp_func: difference}
    - {null_value: 0, alternative: '>', comp_func: relative_change}
    - {null_value: 0, alternative: '<', comp_func: relative_change}
    - {null_value: 0, alternative: '2s', comp_func: relative_change}
  z_confint:
    - {alpha: 0.05, alternative: '2s', comp_func: difference}
    - {alpha: 0.05, alternative: '2s', comp_func: relative_change}
  basic_stats:
