observations_stats:
  t_confint:
    - {alpha: 0.05, alternative: '2s'}
  permutation_confint:
    - {alpha: 0.05, alternative: '2s'}
  basic_stats:


compare_observations:
  t_test:
    - {null_value: 0, alternative: '>', comp_func: difference}
    - {null_value: 0, alternative: '<', comp_func: difference}
    - {null_value: 0, alternative: '2s', comp_func: difference}
    - {null_value: 0, alternative: '>', comp_func: relative_change}
    - {null_value: 0, alternative: '<', comp_func: relative_change}
    - {null_value: 0, alternative: '2s', comp_func: relative_change}
  t_confint:
    - {alpha: 0.05, alternative: '2s', comp_func: difference}
    - {alpha: 0.05, alternative: '2s', comp_func: relative_change}
  mann_whitney_u_test:
    - {alternative: '>'}
    - {alternative: '<'}
    - {alternative: '2s'}
  permutation_test:
    - {null_value: 0, comp_func: difference, stat_func: mean, alternative: '>'}
    - {null_value: 0, comp_func: difference, stat_func: mean, alternative: '<'}
    - {null_value: 0, comp_func: difference, stat_func: mean, alternative: '2s'}
    - {null_value: 0, comp_func: relative_change, stat_func: mean, alternative: '>'}
    - {null_value: 0, comp_func: relative_change, stat_func: mean, alternative: '<'}
    - {null_value: 0, comp_func: relative_change, stat_func: mean, alternative: '2s'}
  permutation_confint:
    - {alpha: 0.05, comp_func: difference, stat_func: mean, alternative: '2s'}
    - {alpha: 0.05, comp_func: relative_change, stat_func: mean, alternative: '2s'}
  basic_stats:
