observations_stats:
  proportion_confint:
    - {alpha: 0.05, alternative: '2s'}
  basic_stats:
  smart_stats:
    - {stat_func: mean}


compare_observations:
  z_test:
    - {null_value: 0, alternative: '>', comp_func: difference}
    - {null_value: 0, alternative: '<', comp_func: difference}
    - {null_value: 0, alternative: '2s', comp_func: difference}
  z_confint:
    - {alpha: 0.05, alternative: '2s', comp_func: difference}
  basic_stats_pooled:
  smart_stats_pooled:
    - {stat_func: mean}
  smart_stats:
    - {comp_func: 'difference', stat_func: mean}
