observations_stats:
  t_confint:
    - {alpha: 0.05, alternative: '2s'}
  basic_stats:
  smart_stats:
    - {stat_func: mean}


compare_observations:
  t_test:
    - {null_value: 0, alternative: '>', comp_func: difference}
    - {null_value: 0, alternative: '<', comp_func: difference}
    - {null_value: 0, alternative: '2s', comp_func: difference}
    - {null_value: 0, alternative: '>', comp_func: relative_change}
    - {null_value: 0, alternative: '<', comp_func: relative_change}
    - {null_value: 0, alternative: '2s', comp_func: relative_change}
  t_confint:
    - {alpha: 0.05, alternative: '2s', comp_func: difference}
    - {alpha: 0.05, alternative: '2s', comp_func: relative_change}
  mann_whitney_u_test:
    - {alternative: '>'}
    - {alternative: '<'}
    - {alternative: '2s'}
  basic_stats:
  smart_stats:
    - {comp_func: 'difference', stat_func: mean}
    - {comp_func: 'relative_change', stat_func: mean}
