metric.counter:
  avitopro_calls_download:                 {obs: [avitopro_calls_download]}
  avitopro_calls_open:                     {obs: [avitopro_calls_open]}
  avitopro_calls_recordplay:               {obs: [avitopro_calls_recordplay]}
  avitopro_item_activate:                  {obs: [avitopro_item_activate]}
  avitopro_item_activateautopublish:       {obs: [avitopro_item_activateautopublish]}
  avitopro_item_deactivate:                {obs: [avitopro_item_deactivate]}
  avitopro_item_deactivateautopublish:     {obs: [avitopro_item_deactivateautopublish]}
  avitopro_item_delete:                    {obs: [avitopro_item_delete]}
  avitopro_item_edit:                      {obs: [avitopro_item_edit]}
  avitopro_item_graph_open:                {obs: [avitopro_item_graph_open]}
  avitopro_item_priceedit:                 {obs: [avitopro_item_priceedit]}
  avitopro_item_responsibleemployee:       {obs: [avitopro_item_responsibleemployee]}
  avitopro_items_open:                     {obs: [avitopro_items_open]}
  avitopro_statistic_download:             {obs: [avitopro_statistic_download]}
  avitopro_statistics_open:                {obs: [avitopro_statistics_open]}
  avitopro_vas_apply:                      {obs: [avitopro_vas_apply]}
  users_avitopro:                          {obs: [users_avitopro]}
  users_avitopro_key_actions:              {obs: [users_avitopro_key_actions]}

metric.uniq:
  avitopro_calls_download_0:               {counter: avitopro_calls_download,         key: [user]}
  avitopro_calls_open_0:                   {counter: avitopro_calls_open,             key: [user]}
  avitopro_calls_recordplay_0:             {counter: avitopro_calls_recordplay,       key: [user]}
  avitopro_item_activate_0:                {counter: avitopro_item_activate,          key: [user]}
  avitopro_item_activateautopublish_0:     {counter: avitopro_item_activateautopublish, key: [user]}
  avitopro_item_deactivate_0:              {counter: avitopro_item_deactivate,        key: [user]}
  avitopro_item_deactivateautopublish_0:   {counter: avitopro_item_deactivateautopublish, key: [user]}
  avitopro_item_delete_0:                  {counter: avitopro_item_delete,            key: [user]}
  avitopro_item_edit_0:                    {counter: avitopro_item_edit,              key: [user]}
  avitopro_item_graph_open_0:              {counter: avitopro_item_graph_open,        key: [user]}
  avitopro_item_priceedit_0:               {counter: avitopro_item_priceedit,         key: [user]}
  avitopro_item_responsibleemployee_0:     {counter: avitopro_item_responsibleemployee, key: [user]}
  avitopro_items_open_0:                   {counter: avitopro_items_open,             key: [user]}
  avitopro_statistic_download_0:           {counter: avitopro_statistic_download,     key: [user]}
  avitopro_statistics_open_0:              {counter: avitopro_statistics_open,        key: [user]}
  avitopro_vas_apply_0:                    {counter: avitopro_vas_apply,              key: [user]}
  users_avitopro_0:                        {counter: users_avitopro,                  key: [user]}
  users_avitopro_key_actions_0:            {counter: users_avitopro_key_actions,      key: [user]}

