metric.counter:
  cnt_avitopro_calls_download:             {obs: [avitopro_calls_download]}
  cnt_avitopro_calls_open:                 {obs: [avitopro_calls_open]}
  cnt_avitopro_calls_recordplay:           {obs: [avitopro_calls_recordplay]}
  cnt_avitopro_item_activate:              {obs: [avitopro_item_activate]}
  cnt_avitopro_item_activateautopublish:   {obs: [avitopro_item_activateautopublish]}
  cnt_avitopro_item_deactivate:            {obs: [avitopro_item_deactivate]}
  cnt_avitopro_item_deactivateautopublish: {obs: [avitopro_item_deactivateautopublish]}
  cnt_avitopro_item_delete:                {obs: [avitopro_item_delete]}
  cnt_avitopro_item_edit:                  {obs: [avitopro_item_edit]}
  cnt_avitopro_item_graph_open:            {obs: [avitopro_item_graph_open]}
  cnt_avitopro_item_priceedit:             {obs: [avitopro_item_priceedit]}
  cnt_avitopro_item_responsibleemployee:   {obs: [avitopro_item_responsibleemployee]}
  cnt_avitopro_items_open:                 {obs: [avitopro_items_open]}
  cnt_avitopro_statistic_download:         {obs: [avitopro_statistic_download]}
  cnt_avitopro_statistics_open:            {obs: [avitopro_statistics_open]}
  cnt_avitopro_vas_apply:                  {obs: [avitopro_vas_apply]}
  cnt_users_avitopro:                      {obs: [users_avitopro]}
  cnt_users_avitopro_key_actions:          {obs: [users_avitopro_key_actions]}

metric.uniq:
  avitopro_calls_download:                 {counter: cnt_avitopro_calls_download,     key: [user]}
  avitopro_calls_open:                     {counter: cnt_avitopro_calls_open,         key: [user]}
  avitopro_calls_recordplay:               {counter: cnt_avitopro_calls_recordplay,   key: [user]}
  avitopro_item_activate:                  {counter: cnt_avitopro_item_activate,      key: [user]}
  avitopro_item_activateautopublish:       {counter: cnt_avitopro_item_activateautopublish, key: [user]}
  avitopro_item_deactivate:                {counter: cnt_avitopro_item_deactivate,    key: [user]}
  avitopro_item_deactivateautopublish:     {counter: cnt_avitopro_item_deactivateautopublish, key: [user]}
  avitopro_item_delete:                    {counter: cnt_avitopro_item_delete,        key: [user]}
  avitopro_item_edit:                      {counter: cnt_avitopro_item_edit,          key: [user]}
  avitopro_item_graph_open:                {counter: cnt_avitopro_item_graph_open,    key: [user]}
  avitopro_item_priceedit:                 {counter: cnt_avitopro_item_priceedit,     key: [user]}
  avitopro_item_responsibleemployee:       {counter: cnt_avitopro_item_responsibleemployee, key: [user]}
  avitopro_items_open:                     {counter: cnt_avitopro_items_open,         key: [user]}
  avitopro_statistic_download:             {counter: cnt_avitopro_statistic_download, key: [user]}
  avitopro_statistics_open:                {counter: cnt_avitopro_statistics_open,    key: [user]}
  avitopro_vas_apply:                      {counter: cnt_avitopro_vas_apply,          key: [user]}
  users_avitopro:                          {counter: cnt_users_avitopro,              key: [user]}
  users_avitopro_key_actions:              {counter: cnt_users_avitopro_key_actions,  key: [user]}

