metric.counter:
  active_listers:                          {obs: [active_listers]}
  deactivated_listers:                     {obs: [deactivated_listers]}
  deactivated_listers_changed_segment:     {obs: [deactivated_listers_changed_segment]}
  deactivated_listers_involuntary:         {obs: [deactivated_listers_involuntary]}
  deactivated_listers_voluntary:           {obs: [deactivated_listers_voluntary]}
  new_listers:                             {obs: [new_listers]}

metric.uniq:
  new_listers_0:                           {counter: new_listers,                     key: [user]}

