metric.counter:
  abuses:                                  {obs: [abuses]}
  address_item_page_clicks:                {obs: [address_item_page_clicks]}
  advertisement_page_views:                {obs: [advertisement_page_views]}
  all_main_pages:                          {obs: [head_main_pages, re_main_pages, services_main_pages, transport_main_pages]}
  authorized_page_views:                   {obs: [page_views_authorized]}
  buyer_favouriteseller_add_from_fs:       {obs: [buyer_favouriteseller_add_from_fs]}
  buyer_favouriteseller_add_from_pp:       {obs: [buyer_favouriteseller_add_from_pp]}
  buyer_favouriteseller_add_from_shop:     {obs: [buyer_favouriteseller_add_from_shop]}
  buyer_favouriteseller_delete_from_fs:    {obs: [buyer_favouriteseller_delete_from_fs]}
  buyer_favouriteseller_delete_from_pp:    {obs: [buyer_favouriteseller_delete_from_pp]}
  buyer_favouriteseller_delete_from_shop:  {obs: [buyer_favouriteseller_delete_from_shop]}
  call_phones:                             {obs: [call_phone_screen_views]}
  calls_dialogues:                         {obs: [call_phone_dialogues]}
  chats_deleted:                           {obs: [messenger_chat_deleted]}
  click_back:                              {obs: [click_back_button]}
  contacts_history_open_in_ratings:        {obs: [contacts_history_open_in_ratings]}
  created_reviews_list_open:               {obs: [created_reviews_list_open]}
  domoteka_preview_clicks:                 {obs: [domoteka_preview_clicks]}
  fatal_app_errors:                        {obs: [fatal_app_error]}
  favouriteseller_activities:              {obs: [buyer_favouriteseller_add, buyer_favouriteseller_delete, buyer_favouriteseller_notifications_off, buyer_favouriteseller_notifications_on, user_favouritesellers_open]}
  favouriteseller_adds:                    {obs: [buyer_favouriteseller_add]}
  favouriteseller_deletes:                 {obs: [buyer_favouriteseller_delete]}
  favouriteseller_notifications_offs:      {obs: [buyer_favouriteseller_notifications_off]}
  favouriteseller_notifications_ons:       {obs: [buyer_favouriteseller_notifications_on]}
  favouriteseller_page_opens:              {obs: [user_favouritesellers_open]}
  filters_screen_shows:                    {obs: [filters_screen_shows]}
  forgot_password_count:                   {obs: [forgot_password_count]}
  fullscreen_photo_galeree_close:          {obs: [fullscreen_photo_galeree_close]}
  fullscreen_photo_galeree_open:           {obs: [fullscreen_photo_galeree_open]}
  geo_redirect_disabled:                   {obs: [geo_redirect_disabled]}
  geo_redirect_replace:                    {obs: [geo_redirect_replace]}
  geo_redirect_suggest:                    {obs: [geo_redirect_suggest]}
  geo_redirect_suggest_disabled:           {obs: [geo_redirect_suggest_disabled]}
  head_main_pages:                         {obs: [head_main_pages]}
  items_add_started:                       {obs: [items_add_started]}
  items_added:                             {obs: [items_added]}
  location_suggest_clicks:                 {obs: [location_suggest_clicks]}
  location_text_inputs:                    {obs: [location_text_inputs]}
  map_interaction_on_item:                 {obs: [map_interaction_on_item]}
  misspell_disabled:                       {obs: [misspell_disabled]}
  misspell_replace:                        {obs: [misspell_replace]}
  misspell_suggest:                        {obs: [misspell_suggest]}
  misspell_suggest_disabled:               {obs: [misspell_suggest_disabled]}
  non_fatal_app_errors:                    {obs: [non_fatal_app_error]}
  page_views:                              {obs: [page_views_all]}
  password_restore_request_attempts:       {obs: [password_restore_request_errors, password_restore_requests]}
  password_restore_request_errors:         {obs: [password_restore_request_errors]}
  password_restore_requests:               {obs: [password_restore_requests]}
  photo_listing_full_screen:               {obs: [photo_listing_full_screen]}
  photo_listing_no_full_screen:            {obs: [photo_listing_no_full_screen]}
  photo_zoom_on_item_page:                 {obs: [photo_zoom_on_item_page]}
  public_profile_visit_from_item:          {obs: [public_profile_visit_from_item]}
  public_profile_visit_from_subscribers_list: {obs: [public_profile_visit_from_fs]}
  public_profile_visit_from_subscribers_messenger: {obs: [public_profile_visit_from_subscribers_messenger]}
  public_profile_visit_from_subscriptions_ratings: {obs: [public_profile_visit_from_subscriptions_ratings]}
  public_profile_visit_from_subscriptions_sharing: {obs: [public_profile_visit_from_subscriptions_sharing]}
  re_main_pages:                           {obs: [re_main_pages]}
  realty_dev_phone_views:                  {obs: [realty_development_phone_views]}
  realty_dev_views:                        {obs: [realty_development_views]}
  received_reviews_list_open:              {obs: [received_reviews_list_open]}
  review_add_open_page:                    {obs: [review_add_open_page]}
  review_delete:                           {obs: [review_delete]}
  reviews_list_open:                       {obs: [reviews_list_open]}
  saved_searches_added:                    {obs: [saved_searches_added]}
  saved_searches_email_item_clicks:        {obs: [search_subscription_email_item_clicks]}
  saved_searches_list_views:               {obs: [search_subscription_list_views]}
  saved_searches_notifications_offs:       {obs: [search_subscription_notifications_delete]}
  saved_searches_notifications_ons:        {obs: [search_subscription_notifications_add]}
  saved_searches_removals:                 {obs: [search_subscription_removals]}
  saved_searches_views:                    {obs: [search_subscription_views]}
  search_redirect_disabled:                {obs: [search_redirect_disabled]}
  search_redirect_replace:                 {obs: [search_redirect_replace]}
  seller_own_item_views:                   {obs: [own_item_views]}
  seller_profile_views:                    {obs: [seller_profile_views]}
  services_main_pages:                     {obs: [services_main_pages]}
  shortcut_clicks:                         {obs: [shortcut_clicks]}
  teleport_disabled:                       {obs: [teleport_disabled]}
  teleport_replace:                        {obs: [teleport_replace]}
  teleport_suggest:                        {obs: [teleport_suggest]}
  teleport_suggest_disabled:               {obs: [teleport_suggest_disabled]}
  transport_main_pages:                    {obs: [transport_main_pages]}
  typo_disabled:                           {obs: [typo_disabled]}
  typo_replace:                            {obs: [typo_replace]}
  vertical_main_pages:                     {obs: [re_main_pages, services_main_pages, transport_main_pages]}

metric.uniq:
  daily_active_authorized_users:           {counter: authorized_page_views,           key: [user]}
  daily_active_users:                      {counter: page_views,                      key: [user]}
  sellers_daily:                           {counter: items_added,                     key: [user]}
  sellers_own_item_viewed:                 {counter: seller_own_item_views,           key: [user]}
  sellers_profile_viewed:                  {counter: seller_profile_views,            key: [user]}
  shortcut_users:                          {counter: shortcut_clicks,                 key: [user]}
  user_address_item_page_clicks:           {counter: address_item_page_clicks,        key: [user]}
  user_created_reviews_list_open:          {counter: created_reviews_list_open,       key: [user]}
  user_domoteka_preview_clicks:            {counter: domoteka_preview_clicks,         key: [user]}
  user_filters_screen_shows:               {counter: filters_screen_shows,            key: [user]}
  user_geo_redirect_replace:               {counter: geo_redirect_replace,            key: [user]}
  user_geo_redirect_suggest:               {counter: geo_redirect_suggest,            key: [user]}
  user_map_interaction_on_item:            {counter: map_interaction_on_item,         key: [user]}
  user_misspell_replace:                   {counter: misspell_replace,                key: [user]}
  user_misspell_suggest:                   {counter: misspell_suggest,                key: [user]}
  user_password_restore_request:           {counter: password_restore_requests,       key: [user]}
  user_password_restore_request_attempt:   {counter: password_restore_request_attempts, key: [user]}
  user_received_reviews_list_open:         {counter: received_reviews_list_open,      key: [user]}
  user_review_add_open_page:               {counter: review_add_open_page,            key: [user]}
  user_review_delete:                      {counter: review_delete,                   key: [user]}
  user_reviews_list_open:                  {counter: reviews_list_open,               key: [user]}
  user_search_redirect_replace:            {counter: search_redirect_replace,         key: [user]}
  user_teleport_replace:                   {counter: teleport_replace,                key: [user]}
  user_teleport_suggest:                   {counter: teleport_suggest,                key: [user]}
  user_typo_replace:                       {counter: typo_replace,                    key: [user]}
  users_all_main_page_daily:               {counter: all_main_pages,                  key: [user]}
  users_fatal_app_errors:                  {counter: fatal_app_errors,                key: [user]}
  users_favouriteseller_activity:          {counter: favouriteseller_activities,      key: [user]}
  users_favouriteseller_add:               {counter: favouriteseller_adds,            key: [user]}
  users_favouriteseller_delete:            {counter: favouriteseller_deletes,         key: [user]}
  users_favouriteseller_notifications_off: {counter: favouriteseller_notifications_offs, key: [user]}
  users_favouriteseller_notifications_on:  {counter: favouriteseller_notifications_ons, key: [user]}
  users_favouriteseller_page_open:         {counter: favouriteseller_page_opens,      key: [user]}
  users_head_main_page_daily:              {counter: head_main_pages,                 key: [user]}
  users_item_add_started:                  {counter: items_add_started,               key: [user]}
  users_loc_suggest_clicks:                {counter: location_suggest_clicks,         key: [user]}
  users_non_fatal_app_errors:              {counter: non_fatal_app_errors,            key: [user]}
  users_phone_calls:                       {counter: call_phones,                     key: [user]}
  users_re_main_page_daily:                {counter: re_main_pages,                   key: [user]}
  users_realty_dev_phone_view:             {counter: realty_dev_phone_views,          key: [user]}
  users_realty_dev_view:                   {counter: realty_dev_views,                key: [user]}
  users_saved_searches_added:              {counter: saved_searches_added,            key: [user]}
  users_saved_searches_email_item_click:   {counter: saved_searches_email_item_clicks, key: [user]}
  users_saved_searches_list_view:          {counter: saved_searches_list_views,       key: [user]}
  users_saved_searches_notifications_off:  {counter: saved_searches_notifications_offs, key: [user]}
  users_saved_searches_notifications_on:   {counter: saved_searches_notifications_ons, key: [user]}
  users_saved_searches_removed:            {counter: saved_searches_removals,         key: [user]}
  users_saved_searches_view:               {counter: saved_searches_views,            key: [user]}
  users_services_main_page_daily:          {counter: services_main_pages,             key: [user]}
  users_transport_main_page_daily:         {counter: transport_main_pages,            key: [user]}
  users_vertical_main_page_daily:          {counter: vertical_main_pages,             key: [user]}

metric.ratio:
  authorized_visitors_share:               {num: daily_active_authorized_users,   den: daily_active_users}
  geo_redirect_replace_ctr_disable:        {num: geo_redirect_disabled,           den: geo_redirect_replace}
  geo_redirect_suggest_ctr_disable:        {num: geo_redirect_suggest_disabled,   den: geo_redirect_suggest}
  items_added_per_items_add_started:       {num: items_added,                     den: items_add_started}
  loc_suggests_per_text_inputs:            {num: location_suggest_clicks,         den: location_text_inputs}
  misspell_replace_ctr_disable:            {num: misspell_disabled,               den: misspell_replace}
  misspell_suggest_ctr_disable:            {num: misspell_suggest_disabled,       den: misspell_suggest}
  realty_dev_phone_per_views:              {num: realty_dev_phone_views,          den: realty_dev_views}
  search_redirect_replace_ctr_disable:     {num: search_redirect_disabled,        den: search_redirect_replace}
  teleport_replace_ctr_disable:            {num: teleport_disabled,               den: teleport_replace}
  teleport_suggest_ctr_disable:            {num: teleport_suggest_disabled,       den: teleport_suggest}
  typo_replace_ctr_disable:                {num: typo_disabled,                   den: typo_replace}

