metric.counter:
  cnt_active_buyers_with_fs_subscriptions_share: {obs: [favourite_sellers_subscriptions_active_new, favourite_sellers_subscriptions_active_old]}
  cnt_active_sellers_with_fs_subscribers:  {obs: [favourite_sellers_subscribers_active_new, favourite_sellers_subscribers_active_old]}
  fs_subscribers_per_seller:               {obs: [favourite_sellers_subscribers_active_new, favourite_sellers_subscribers_active_old, favourite_sellers_subscribers_inactive_new, favourite_sellers_subscribers_inactive_old]}
  fs_subscriptions_per_buyer:              {obs: [favourite_sellers_subscriptions_active_new, favourite_sellers_subscriptions_active_old, favourite_sellers_subscriptions_inactive_old]}

metric.uniq:
  active_buyers_with_fs_subscriptions:     {counter: cnt_active_buyers_with_fs_subscriptions_share, key: [user]}
  active_sellers_with_fs_subscribers:      {counter: cnt_active_sellers_with_fs_subscribers, key: [user]}
  buyers_with_fs_subscriptions:            {counter: fs_subscriptions_per_buyer,      key: [user]}
  sellers_with_fs_subscribers:             {counter: fs_subscribers_per_seller,       key: [user]}

