metric.counter:
  cnt_item_address_length:                 {obs: [item_address_length]}
  cnt_item_address_length_new:             {obs: [item_address_length_new]}
  cnt_item_address_length_reactivated:     {obs: [item_address_length_reactivated]}
  items_100m_from_location:                {obs: [item_100m_from_location]}
  items_100m_from_location_new:            {obs: [item_100m_from_location_new]}
  items_100m_from_location_reactivated:    {obs: [item_100m_from_location_reactivated]}
  items_200_plus_km_from_location:         {obs: [item_200_plus_km_from_location]}
  items_200_plus_km_from_location_new:     {obs: [item_200_plus_km_from_location_new]}
  items_200_plus_km_from_location_reactivated: {obs: [item_200_plus_km_from_location_reactivated]}
  items_20m_from_location:                 {obs: [item_20m_from_location]}
  items_20m_from_location_new:             {obs: [item_20m_from_location_new]}
  items_20m_from_location_reactivated:     {obs: [item_20m_from_location_reactivated]}
  items_no_address_id:                     {obs: [item_no_address_id]}
  items_no_address_id_new:                 {obs: [item_no_address_id_new]}
  items_no_address_id_reactivated:         {obs: [item_no_address_id_reactivated]}
  items_no_address_string:                 {obs: [item_no_address_string]}
  items_no_address_string_new:             {obs: [item_no_address_string_new]}
  items_no_address_string_reactivated:     {obs: [item_no_address_string_reactivated]}
  items_no_city:                           {obs: [item_no_city]}
  items_no_city_new:                       {obs: [item_no_city_new]}
  items_no_city_reactivated:               {obs: [item_no_city_reactivated]}
  items_no_coordinates:                    {obs: [item_no_coordinates]}
  items_no_coordinates_new:                {obs: [item_no_coordinates_new]}
  items_no_coordinates_reactivated:        {obs: [item_no_coordinates_reactivated]}
  items_with_address_id:                   {obs: [item_with_address_id]}
  items_with_address_id_new:               {obs: [item_with_address_id_new]}
  items_with_address_id_reactivated:       {obs: [item_with_address_id_reactivated]}
  items_with_address_string:               {obs: [item_with_address_string]}
  items_with_address_string_new:           {obs: [item_with_address_string_new]}
  items_with_address_string_reactivated:   {obs: [item_with_address_string_reactivated]}
  items_with_building:                     {obs: [item_has_building]}
  items_with_building_new:                 {obs: [item_has_building_new]}
  items_with_building_reactivated:         {obs: [item_has_building_reactivated]}
  items_with_city:                         {obs: [item_has_city]}
  items_with_city_new:                     {obs: [item_has_city_new]}
  items_with_city_reactivated:             {obs: [item_has_city_reactivated]}
  items_with_coordinates:                  {obs: [item_with_coordinates]}
  items_with_coordinates_new:              {obs: [item_with_coordinates_new]}
  items_with_coordinates_reactivated:      {obs: [item_with_coordinates_reactivated]}
  items_with_district:                     {obs: [item_has_district]}
  items_with_district_new:                 {obs: [item_has_district_new]}
  items_with_district_reactivated:         {obs: [item_has_district_reactivated]}
  items_with_marginal_address:             {obs: [item_has_marginal_address]}
  items_with_marginal_address_new:         {obs: [item_has_marginal_address_new]}
  items_with_marginal_address_reactivated: {obs: [item_has_marginal_address_reactivated]}
  items_with_street:                       {obs: [item_has_street]}
  items_with_street_new:                   {obs: [item_has_street_new]}
  items_with_street_reactivated:           {obs: [item_has_street_reactivated]}

metric.ratio:
  avg_item_address_length:                 {num: cnt_item_address_length,         den: items_with_address_string}
  avg_item_address_length_new:             {num: cnt_item_address_length_new,     den: items_with_address_string_new}
  avg_item_address_length_react:           {num: cnt_item_address_length_reactivated, den: items_with_address_string_reactivated}

