metric.counter:
  cnt_ad_pages_to_contact:                 {obs: [ad_pages_to_contact]}
  cnt_correct_and_map_searches_and_iv_to_contact: {obs: [correct_and_map_searches_and_iv_to_contact]}
  cnt_correct_searches_and_iv_to_contact:  {obs: [correct_searches_and_iv_to_contact]}
  cnt_correct_searches_to_contact:         {obs: [correct_searches_to_contact]}
  cnt_item_views_to_contact:               {obs: [item_views_to_contact]}
  cnt_map_searches_and_iv_to_contact:      {obs: [map_searches_and_iv_to_contact]}
  cnt_map_searches_to_contact:             {obs: [map_searches_to_contact]}
  cnt_searches_to_contact:                 {obs: [searches_to_contact]}
  from_main_page_to_c:                     {obs: [from_main_page_to_c]}
  from_main_page_to_c_p25:                 {obs: [from_main_page_to_c_p25]}
  from_main_page_to_c_p50:                 {obs: [from_main_page_to_c_p50]}
  from_main_page_to_c_p75:                 {obs: [from_main_page_to_c_p75]}
  from_main_page_to_c_p99:                 {obs: [from_main_page_to_c_p99]}
  from_main_page_to_iv:                    {obs: [from_main_page_to_iv]}
  from_main_page_to_iv_p25:                {obs: [from_main_page_to_iv_p25]}
  from_main_page_to_iv_p50:                {obs: [from_main_page_to_iv_p50]}
  from_main_page_to_iv_p75:                {obs: [from_main_page_to_iv_p75]}
  from_main_page_to_iv_p99:                {obs: [from_main_page_to_iv_p99]}
  from_session_start_to_c:                 {obs: [from_session_start_to_c]}
  from_session_start_to_c_p25:             {obs: [from_session_start_to_c_p25]}
  from_session_start_to_c_p50:             {obs: [from_session_start_to_c_p50]}
  from_session_start_to_c_p75:             {obs: [from_session_start_to_c_p75]}
  from_session_start_to_c_p99:             {obs: [from_session_start_to_c_p99]}
  from_session_start_to_iv:                {obs: [from_session_start_to_iv]}
  from_session_start_to_iv_p25:            {obs: [from_session_start_to_iv_p25]}
  from_session_start_to_iv_p50:            {obs: [from_session_start_to_iv_p50]}
  from_session_start_to_iv_p75:            {obs: [from_session_start_to_iv_p75]}
  from_session_start_to_iv_p99:            {obs: [from_session_start_to_iv_p99]}
  from_vertical_page_to_c:                 {obs: [from_vertical_page_to_c]}
  from_vertical_page_to_c_p25:             {obs: [from_vertical_page_to_c_p25]}
  from_vertical_page_to_c_p50:             {obs: [from_vertical_page_to_c_p50]}
  from_vertical_page_to_c_p75:             {obs: [from_vertical_page_to_c_p75]}
  from_vertical_page_to_c_p99:             {obs: [from_vertical_page_to_c_p99]}
  from_vertical_page_to_iv:                {obs: [from_vertical_page_to_iv]}
  from_vertical_page_to_iv_p25:            {obs: [from_vertical_page_to_iv_p25]}
  from_vertical_page_to_iv_p50:            {obs: [from_vertical_page_to_iv_p50]}
  from_vertical_page_to_iv_p75:            {obs: [from_vertical_page_to_iv_p75]}
  from_vertical_page_to_iv_p99:            {obs: [from_vertical_page_to_iv_p99]}
  searches_and_iv_to_contact:              {obs: [searches_and_iv_to_contact]}

metric.uniq:
  user_from_main_page_to_c_p25:            {counter: from_main_page_to_c_p25,         key: [user]}
  user_from_main_page_to_c_p50:            {counter: from_main_page_to_c_p50,         key: [user]}
  user_from_main_page_to_c_p75:            {counter: from_main_page_to_c_p75,         key: [user]}
  user_from_main_page_to_c_p99:            {counter: from_main_page_to_c_p99,         key: [user]}
  user_from_main_page_to_iv_p25:           {counter: from_main_page_to_iv_p25,        key: [user]}
  user_from_main_page_to_iv_p50:           {counter: from_main_page_to_iv_p50,        key: [user]}
  user_from_main_page_to_iv_p75:           {counter: from_main_page_to_iv_p75,        key: [user]}
  user_from_main_page_to_iv_p99:           {counter: from_main_page_to_iv_p99,        key: [user]}
  user_from_session_start_to_c_p25:        {counter: from_session_start_to_c_p25,     key: [user]}
  user_from_session_start_to_c_p50:        {counter: from_session_start_to_c_p50,     key: [user]}
  user_from_session_start_to_c_p75:        {counter: from_session_start_to_c_p75,     key: [user]}
  user_from_session_start_to_c_p99:        {counter: from_session_start_to_c_p99,     key: [user]}
  user_from_session_start_to_iv_p25:       {counter: from_session_start_to_iv_p25,    key: [user]}
  user_from_session_start_to_iv_p50:       {counter: from_session_start_to_iv_p50,    key: [user]}
  user_from_session_start_to_iv_p75:       {counter: from_session_start_to_iv_p75,    key: [user]}
  user_from_session_start_to_iv_p99:       {counter: from_session_start_to_iv_p99,    key: [user]}
  user_from_vertical_page_to_c_p25:        {counter: from_vertical_page_to_c_p25,     key: [user]}
  user_from_vertical_page_to_c_p50:        {counter: from_vertical_page_to_c_p50,     key: [user]}
  user_from_vertical_page_to_c_p75:        {counter: from_vertical_page_to_c_p75,     key: [user]}
  user_from_vertical_page_to_c_p99:        {counter: from_vertical_page_to_c_p99,     key: [user]}
  user_from_vertical_page_to_iv_p25:       {counter: from_vertical_page_to_iv_p25,    key: [user]}
  user_from_vertical_page_to_iv_p50:       {counter: from_vertical_page_to_iv_p50,    key: [user]}
  user_from_vertical_page_to_iv_p75:       {counter: from_vertical_page_to_iv_p75,    key: [user]}
  user_from_vertical_page_to_iv_p99:       {counter: from_vertical_page_to_iv_p99,    key: [user]}
  session_from_main_page_to_c:             {counter: from_main_page_to_c,             key: [user, session]}
  session_from_main_page_to_iv:            {counter: from_main_page_to_iv,            key: [user, session]}
  session_from_session_start_to_c:         {counter: from_session_start_to_c,         key: [user, session]}
  session_from_session_start_to_iv:        {counter: from_session_start_to_iv,        key: [user, session]}
  session_from_vertical_page_to_c:         {counter: from_vertical_page_to_c,         key: [user, session]}
  session_from_vertical_page_to_iv:        {counter: from_vertical_page_to_iv,        key: [user, session]}

