metric.counter:
  ancalls_any_type:                        {obs: [anon_calls_matched_any_type]}
  ancalls_any_type_fav:                    {obs: [anon_calls_matched_any_type_fav]}
  ancalls_any_type_map:                    {obs: [anon_calls_matched_any_type_map]}
  ancalls_any_type_rec:                    {obs: [anon_calls_matched_any_type_rec]}
  ancalls_any_type_serp:                   {obs: [anon_calls_matched_any_type_serp]}
  ancalls_both_types:                      {obs: [anon_calls_matched_both_types]}
  ancalls_both_types_fav:                  {obs: [anon_calls_matched_both_types_fav]}
  ancalls_both_types_map:                  {obs: [anon_calls_matched_both_types_map]}
  ancalls_both_types_rec:                  {obs: [anon_calls_matched_both_types_rec]}
  ancalls_both_types_serp:                 {obs: [anon_calls_matched_both_types_serp]}
  ancalls_by_phone:                        {obs: [anon_calls_matched_by_phone]}
  ancalls_by_phone_fav:                    {obs: [anon_calls_matched_by_phone_fav]}
  ancalls_by_phone_map:                    {obs: [anon_calls_matched_by_phone_map]}
  ancalls_by_phone_rec:                    {obs: [anon_calls_matched_by_phone_rec]}
  ancalls_by_phone_serp:                   {obs: [anon_calls_matched_by_phone_serp]}
  ancalls_by_phone_uid:                    {obs: [anon_calls_matched_by_phone_and_user]}
  ancalls_by_phone_uid_fav:                {obs: [anon_calls_matched_by_phone_and_user_fav]}
  ancalls_by_phone_uid_map:                {obs: [anon_calls_matched_by_phone_and_user_map]}
  ancalls_by_phone_uid_rec:                {obs: [anon_calls_matched_by_phone_and_user_rec]}
  ancalls_by_phone_uid_serp:               {obs: [anon_calls_matched_by_phone_and_user_serp]}
  ancalls_by_time:                         {obs: [anon_calls_matched_by_time]}
  ancalls_by_time_fav:                     {obs: [anon_calls_matched_by_time_fav]}
  ancalls_by_time_map:                     {obs: [anon_calls_matched_by_time_map]}
  ancalls_by_time_rec:                     {obs: [anon_calls_matched_by_time_rec]}
  ancalls_by_time_serp:                    {obs: [anon_calls_matched_by_time_serp]}
  answered_proxy_calls:                    {obs: [answered_proxy_calls]}
  answered_proxy_calls_fav:                {obs: [answered_proxy_calls_fav]}
  answered_proxy_calls_map:                {obs: [answered_proxy_calls_map]}
  answered_proxy_calls_rec:                {obs: [answered_proxy_calls_rec]}
  answered_proxy_calls_serp:               {obs: [answered_proxy_calls_serp]}
  calls_fav:                               {obs: [answered_proxy_calls_fav, missed_proxy_calls_fav]}
  calls_map:                               {obs: [answered_proxy_calls_map, missed_proxy_calls_map]}
  calls_rec:                               {obs: [answered_proxy_calls_rec, missed_proxy_calls_rec]}
  calls_serp:                              {obs: [answered_proxy_calls_serp, missed_proxy_calls_serp]}
  missed_proxy_calls:                      {obs: [missed_proxy_calls]}
  missed_proxy_calls_fav:                  {obs: [missed_proxy_calls_fav]}
  missed_proxy_calls_map:                  {obs: [missed_proxy_calls_map]}
  missed_proxy_calls_rec:                  {obs: [missed_proxy_calls_rec]}
  missed_proxy_calls_serp:                 {obs: [missed_proxy_calls_serp]}

metric.uniq:
  users_ancalls_any_type:                  {counter: ancalls_any_type,                key: [user]}
  users_ancalls_both_types:                {counter: ancalls_both_types,              key: [user]}
  users_ancalls_by_phone:                  {counter: ancalls_by_phone,                key: [user]}
  users_ancalls_by_phone_uid:              {counter: ancalls_by_phone_uid,            key: [user]}
  users_ancalls_by_time:                   {counter: ancalls_by_time,                 key: [user]}
  users_phone_calls_client_fav:            {counter: calls_fav,                       key: [user]}
  users_phone_calls_client_map:            {counter: calls_map,                       key: [user]}
  users_phone_calls_client_serp:           {counter: calls_serp,                      key: [user]}

