metric.counter:
  vas_amount:                              {obs: [vas_amount]}
  vas_amount_activation:                   {obs: [vas_amount_activation]}
  vas_amount_activation_start_date:        {filter: {<<: *start}, obs: [vas_amount_activation]}
  vas_amount_fast:                         {obs: [vas_amount_fast]}
  vas_amount_fast_start_date:              {filter: {<<: *start}, obs: [vas_amount_fast]}
  vas_amount_highlight:                    {obs: [vas_amount_highlight]}
  vas_amount_highlight_start_date:         {filter: {<<: *start}, obs: [vas_amount_highlight]}
  vas_amount_net:                          {obs: [vas_amount_net]}
  vas_amount_net_activation:               {obs: [vas_amount_net_activation]}
  vas_amount_net_activation_start_date:    {filter: {<<: *start}, obs: [vas_amount_net_activation]}
  vas_amount_net_fast:                     {obs: [vas_amount_net_fast]}
  vas_amount_net_fast_start_date:          {filter: {<<: *start}, obs: [vas_amount_net_fast]}
  vas_amount_net_highlight:                {obs: [vas_amount_net_highlight]}
  vas_amount_net_highlight_start_date:     {filter: {<<: *start}, obs: [vas_amount_net_highlight]}
  vas_amount_net_premium:                  {obs: [vas_amount_net_premium]}
  vas_amount_net_premium_start_date:       {filter: {<<: *start}, obs: [vas_amount_net_premium]}
  vas_amount_net_pushup:                   {obs: [vas_amount_net_pushup]}
  vas_amount_net_pushup_start_date:        {filter: {<<: *start}, obs: [vas_amount_net_pushup]}
  vas_amount_net_start_date:               {filter: {<<: *start}, obs: [vas_amount_net]}
  vas_amount_net_turbo:                    {obs: [vas_amount_net_turbo]}
  vas_amount_net_turbo_start_date:         {filter: {<<: *start}, obs: [vas_amount_net_turbo]}
  vas_amount_net_vip:                      {obs: [vas_amount_net_vip]}
  vas_amount_net_vip_start_date:           {filter: {<<: *start}, obs: [vas_amount_net_vip]}
  vas_amount_net_xl:                       {obs: [vas_amount_net_xl]}
  vas_amount_net_xl_start_date:            {filter: {<<: *start}, obs: [vas_amount_net_xl]}
  vas_amount_premium:                      {obs: [vas_amount_premium]}
  vas_amount_premium_start_date:           {filter: {<<: *start}, obs: [vas_amount_premium]}
  vas_amount_pushup:                       {obs: [vas_amount_pushup]}
  vas_amount_pushup_start_date:            {filter: {<<: *start}, obs: [vas_amount_pushup]}
  vas_amount_start_date:                   {filter: {<<: *start}, obs: [vas_amount]}
  vas_amount_turbo:                        {obs: [vas_amount_turbo]}
  vas_amount_turbo_start_date:             {filter: {<<: *start}, obs: [vas_amount_turbo]}
  vas_amount_vip:                          {obs: [vas_amount_vip]}
  vas_amount_vip_start_date:               {filter: {<<: *start}, obs: [vas_amount_vip]}
  vas_amount_xl:                           {obs: [vas_amount_xl]}
  vas_amount_xl_start_date:                {filter: {<<: *start}, obs: [vas_amount_xl]}
  vas_transactions:                        {obs: [vas_transactions]}
  vas_transactions_activation:             {obs: [vas_transactions_activation]}
  vas_transactions_activation_start_date:  {filter: {<<: *start}, obs: [vas_transactions_activation]}
  vas_transactions_fast:                   {obs: [vas_transactions_fast]}
  vas_transactions_fast_start_date:        {filter: {<<: *start}, obs: [vas_transactions_fast]}
  vas_transactions_highlight:              {obs: [vas_transactions_highlight]}
  vas_transactions_highlight_start_date:   {filter: {<<: *start}, obs: [vas_transactions_highlight]}
  vas_transactions_premium:                {obs: [vas_transactions_premium]}
  vas_transactions_premium_start_date:     {filter: {<<: *start}, obs: [vas_transactions_premium]}
  vas_transactions_pushup:                 {obs: [vas_transactions_pushup]}
  vas_transactions_pushup_start_date:      {filter: {<<: *start}, obs: [vas_transactions_pushup]}
  vas_transactions_start_date:             {filter: {<<: *start}, obs: [vas_transactions]}
  vas_transactions_turbo:                  {obs: [vas_transactions_turbo]}
  vas_transactions_turbo_start_date:       {filter: {<<: *start}, obs: [vas_transactions_turbo]}
  vas_transactions_vip:                    {obs: [vas_transactions_vip]}
  vas_transactions_vip_start_date:         {filter: {<<: *start}, obs: [vas_transactions_vip]}
  vas_transactions_xl:                     {obs: [vas_transactions_xl]}
  vas_transactions_xl_start_date:          {filter: {<<: *start}, obs: [vas_transactions_xl]}

metric.uniq:
  users_vas:                               {counter: vas_amount_net,                  key: [user]}
  users_vas_activation:                    {counter: vas_amount_net_activation,       key: [user]}
  users_vas_activation_start_date:         {counter: vas_amount_net_activation_start_date, key: [user]}
  users_vas_fast:                          {counter: vas_amount_net_fast,             key: [user]}
  users_vas_fast_start_date:               {counter: vas_amount_net_fast_start_date,  key: [user]}
  users_vas_highlight:                     {counter: vas_amount_net_highlight,        key: [user]}
  users_vas_highlight_start_date:          {counter: vas_amount_net_highlight_start_date, key: [user]}
  users_vas_premium:                       {counter: vas_amount_net_premium,          key: [user]}
  users_vas_premium_start_date:            {counter: vas_amount_net_premium_start_date, key: [user]}
  users_vas_pushup:                        {counter: vas_amount_net_pushup,           key: [user]}
  users_vas_pushup_start_date:             {counter: vas_amount_net_pushup_start_date, key: [user]}
  users_vas_start_date:                    {counter: vas_amount_net_start_date,       key: [user]}
  users_vas_turbo:                         {counter: vas_amount_net_turbo,            key: [user]}
  users_vas_turbo_start_date:              {counter: vas_amount_net_turbo_start_date, key: [user]}
  users_vas_vip:                           {counter: vas_amount_net_vip,              key: [user]}
  users_vas_vip_start_date:                {counter: vas_amount_net_vip_start_date,   key: [user]}
  users_vas_xl:                            {counter: vas_amount_net_xl,               key: [user]}
  users_vas_xl_start_date:                 {counter: vas_amount_net_xl_start_date,    key: [user]}

metric.ratio:
  vas_avo:                                 {num: vas_amount,                      den: vas_transactions}
  vas_avo_activation:                      {num: vas_amount_activation,           den: vas_transactions_activation}
  vas_avo_activation_start_date:           {num: vas_amount_activation_start_date, den: vas_transactions_activation_start_date}
  vas_avo_fast:                            {num: vas_amount_fast,                 den: vas_transactions_fast}
  vas_avo_fast_start_date:                 {num: vas_amount_fast_start_date,      den: vas_transactions_fast_start_date}
  vas_avo_highlight:                       {num: vas_amount_highlight,            den: vas_transactions_highlight}
  vas_avo_highlight_start_date:            {num: vas_amount_highlight_start_date, den: vas_transactions_highlight_start_date}
  vas_avo_net:                             {num: vas_amount_net,                  den: vas_transactions}
  vas_avo_net_activation:                  {num: vas_amount_net_activation,       den: vas_transactions_activation}
  vas_avo_net_activation_start_date:       {num: vas_amount_net_activation_start_date, den: vas_transactions_activation_start_date}
  vas_avo_net_fast:                        {num: vas_amount_net_fast,             den: vas_transactions_fast}
  vas_avo_net_fast_start_date:             {num: vas_amount_net_fast_start_date,  den: vas_transactions_fast_start_date}
  vas_avo_net_highlight:                   {num: vas_amount_net_highlight,        den: vas_transactions_highlight}
  vas_avo_net_highlight_start_date:        {num: vas_amount_net_highlight_start_date, den: vas_transactions_highlight_start_date}
  vas_avo_net_premium:                     {num: vas_amount_net_premium,          den: vas_transactions_premium}
  vas_avo_net_premium_start_date:          {num: vas_amount_net_premium_start_date, den: vas_transactions_premium_start_date}
  vas_avo_net_pushup:                      {num: vas_amount_net_pushup,           den: vas_transactions_pushup}
  vas_avo_net_pushup_start_date:           {num: vas_amount_net_pushup_start_date, den: vas_transactions_pushup_start_date}
  vas_avo_net_start_date:                  {num: vas_amount_net_start_date,       den: vas_transactions_start_date}
  vas_avo_net_turbo:                       {num: vas_amount_net_turbo,            den: vas_transactions_turbo}
  vas_avo_net_turbo_start_date:            {num: vas_amount_net_turbo_start_date, den: vas_transactions_turbo_start_date}
  vas_avo_net_vip:                         {num: vas_amount_net_vip,              den: vas_transactions_vip}
  vas_avo_net_vip_start_date:              {num: vas_amount_net_vip_start_date,   den: vas_transactions_vip_start_date}
  vas_avo_net_xl:                          {num: vas_amount_net_xl,               den: vas_transactions_xl}
  vas_avo_net_xl_start_date:               {num: vas_amount_net_xl_start_date,    den: vas_transactions_xl_start_date}
  vas_avo_premium:                         {num: vas_amount_premium,              den: vas_transactions_premium}
  vas_avo_premium_start_date:              {num: vas_amount_premium_start_date,   den: vas_transactions_premium_start_date}
  vas_avo_pushup:                          {num: vas_amount_pushup,               den: vas_transactions_pushup}
  vas_avo_pushup_start_date:               {num: vas_amount_pushup_start_date,    den: vas_transactions_pushup_start_date}
  vas_avo_start_date:                      {num: vas_amount_start_date,           den: vas_transactions_start_date}
  vas_avo_turbo:                           {num: vas_amount_turbo,                den: vas_transactions_turbo}
  vas_avo_turbo_start_date:                {num: vas_amount_turbo_start_date,     den: vas_transactions_turbo_start_date}
  vas_avo_vip:                             {num: vas_amount_vip,                  den: vas_transactions_vip}
  vas_avo_vip_start_date:                  {num: vas_amount_vip_start_date,       den: vas_transactions_vip_start_date}
  vas_avo_xl:                              {num: vas_amount_xl,                   den: vas_transactions_xl}
  vas_avo_xl_start_date:                   {num: vas_amount_xl_start_date,        den: vas_transactions_xl_start_date}

