metric.counter:
  cnt_di_session_duration:                 {obs: [di_session_duration]}
  cnt_draw_appstart_session_duration:      {obs: [draw_appstart_session_duration]}
  cnt_draw_duration:                       {obs: [draw_duration]}
  cnt_draw_session_duration:               {obs: [draw_session_duration]}
  cnt_init_appstart_session_duration:      {obs: [init_appstart_session_duration]}
  cnt_init_duration:                       {obs: [init_duration]}
  cnt_init_session_duration:               {obs: [init_session_duration]}
  cnt_localloading_duration:               {obs: [localloading_duration]}
  cnt_localloading_session_duration:       {obs: [localloading_session_duration]}
  cnt_prepare_duration:                    {obs: [prepare_duration]}
  cnt_prepare_session_duration:            {obs: [prepare_session_duration]}
  cnt_serverloading_duration:              {obs: [serverloading_duration]}
  cnt_serverloading_session_duration:      {obs: [serverloading_session_duration]}
  di_events:                               {obs: [di_events]}
  di_events_p25:                           {obs: [di_events_p25]}
  di_events_p50:                           {obs: [di_events_p50]}
  di_events_p75:                           {obs: [di_events_p75]}
  di_events_p95:                           {obs: [di_events_p95]}
  di_session_duration_events:              {obs: [di_session_duration_events]}
  draw_appstart_session_duration_events:   {obs: [draw_appstart_session_duration_events]}
  draw_appstart_sessions:                  {obs: [draw_appstart_sessions]}
  draw_appstart_sessions_p25:              {obs: [draw_appstart_sessions_p25]}
  draw_appstart_sessions_p50:              {obs: [draw_appstart_sessions_p50]}
  draw_appstart_sessions_p75:              {obs: [draw_appstart_sessions_p75]}
  draw_appstart_sessions_p95:              {obs: [draw_appstart_sessions_p95]}
  draw_duration_events:                    {obs: [draw_duration_events]}
  draw_events:                             {obs: [draw_events]}
  draw_events_draw_exceptions:             {obs: [draw_events, draw_exceptions]}
  draw_events_p25:                         {obs: [draw_events_p25]}
  draw_events_p50:                         {obs: [draw_events_p50]}
  draw_events_p75:                         {obs: [draw_events_p75]}
  draw_events_p95:                         {obs: [draw_events_p95]}
  draw_exceptions:                         {obs: [draw_exceptions]}
  draw_session_duration_events:            {obs: [draw_session_duration_events]}
  draw_sessions:                           {obs: [draw_sessions]}
  draw_sessions_p25:                       {obs: [draw_sessions_p25]}
  draw_sessions_p50:                       {obs: [draw_sessions_p50]}
  draw_sessions_p75:                       {obs: [draw_sessions_p75]}
  draw_sessions_p95:                       {obs: [draw_sessions_p95]}
  draw_sessions_sla:                       {obs: [draw_sessions_sla]}
  init_appstart_session_duration_events:   {obs: [init_appstart_session_duration_events]}
  init_appstart_sessions:                  {obs: [init_appstart_sessions]}
  init_appstart_sessions_p25:              {obs: [init_appstart_sessions_p25]}
  init_appstart_sessions_p50:              {obs: [init_appstart_sessions_p50]}
  init_appstart_sessions_p75:              {obs: [init_appstart_sessions_p75]}
  init_appstart_sessions_p95:              {obs: [init_appstart_sessions_p95]}
  init_duration_events:                    {obs: [init_duration_events]}
  init_events:                             {obs: [init_events]}
  init_events_p25:                         {obs: [init_events_p25]}
  init_events_p50:                         {obs: [init_events_p50]}
  init_events_p75:                         {obs: [init_events_p75]}
  init_events_p95:                         {obs: [init_events_p95]}
  init_session_duration_events:            {obs: [init_session_duration_events]}
  init_sessions:                           {obs: [init_sessions]}
  init_sessions_p25:                       {obs: [init_sessions_p25]}
  init_sessions_p50:                       {obs: [init_sessions_p50]}
  init_sessions_p75:                       {obs: [init_sessions_p75]}
  init_sessions_p95:                       {obs: [init_sessions_p95]}
  init_sessions_sla:                       {obs: [init_sessions_sla]}
  localloading_duration_events:            {obs: [localloading_duration_events]}
  localloading_events:                     {obs: [localloading_events]}
  localloading_events_p50:                 {obs: [localloading_events_p50]}
  localloading_events_p75:                 {obs: [localloading_events_p75]}
  localloading_events_p95:                 {obs: [localloading_events_p95]}
  localloading_session_duration_events:    {obs: [localloading_session_duration_events]}
  prepare_duration_events:                 {obs: [prepare_duration_events]}
  prepare_events:                          {obs: [prepare_events]}
  prepare_events_p50:                      {obs: [prepare_events_p50]}
  prepare_events_p75:                      {obs: [prepare_events_p75]}
  prepare_events_p95:                      {obs: [prepare_events_p95]}
  prepare_events_prepare_exceptions:       {obs: [prepare_events, prepare_exceptions]}
  prepare_exceptions:                      {obs: [prepare_exceptions]}
  prepare_session_duration_events:         {obs: [prepare_session_duration_events]}
  serverloading_duration_events:           {obs: [serverloading_duration_events]}
  serverloading_events:                    {obs: [serverloading_events]}
  serverloading_events_p25:                {obs: [serverloading_events_p25]}
  serverloading_events_p50:                {obs: [serverloading_events_p50]}
  serverloading_events_p75:                {obs: [serverloading_events_p75]}
  serverloading_events_p95:                {obs: [serverloading_events_p95]}
  serverloading_events_serverloading_exceptions: {obs: [serverloading_events, serverloading_exceptions]}
  serverloading_exceptions:                {obs: [serverloading_exceptions]}
  serverloading_session_duration_events:   {obs: [serverloading_session_duration_events]}

metric.ratio:
  bounce_rate_perf:                        {num: draw_events,                     den: init_events}
  di_percent_p25:                          {num: di_events_p25,                   den: di_events}
  di_percent_p50:                          {num: di_events_p50,                   den: di_events}
  di_percent_p75:                          {num: di_events_p75,                   den: di_events}
  di_percent_p95:                          {num: di_events_p95,                   den: di_events}
  di_session_duration:                     {num: cnt_di_session_duration,         den: di_session_duration_events}
  draw_appstart_session_duration:          {num: cnt_draw_appstart_session_duration, den: draw_appstart_session_duration_events}
  draw_appstart_session_percent_p25:       {num: draw_appstart_sessions_p25,      den: draw_appstart_sessions}
  draw_appstart_session_percent_p50:       {num: draw_appstart_sessions_p50,      den: draw_appstart_sessions}
  draw_appstart_session_percent_p75:       {num: draw_appstart_sessions_p75,      den: draw_appstart_sessions}
  draw_appstart_session_percent_p95:       {num: draw_appstart_sessions_p95,      den: draw_appstart_sessions}
  draw_duration:                           {num: cnt_draw_duration,               den: draw_duration_events}
  draw_percent_exceptions:                 {num: draw_exceptions,                 den: draw_events_draw_exceptions}
  draw_percent_p25:                        {num: draw_events_p25,                 den: draw_events}
  draw_percent_p50:                        {num: draw_events_p50,                 den: draw_events}
  draw_percent_p75:                        {num: draw_events_p75,                 den: draw_events}
  draw_percent_p95:                        {num: draw_events_p95,                 den: draw_events}
  draw_session_duration:                   {num: cnt_draw_session_duration,       den: draw_session_duration_events}
  draw_session_percent_p25:                {num: draw_sessions_p25,               den: draw_sessions}
  draw_session_percent_p50:                {num: draw_sessions_p50,               den: draw_sessions}
  draw_session_percent_p75:                {num: draw_sessions_p75,               den: draw_sessions}
  draw_session_percent_p95:                {num: draw_sessions_p95,               den: draw_sessions}
  draw_session_percent_sla:                {num: draw_sessions_sla,               den: draw_sessions}
  init_appstart_session_duration:          {num: cnt_init_appstart_session_duration, den: init_appstart_session_duration_events}
  init_appstart_session_percent_p25:       {num: init_appstart_sessions_p25,      den: init_appstart_sessions}
  init_appstart_session_percent_p50:       {num: init_appstart_sessions_p50,      den: init_appstart_sessions}
  init_appstart_session_percent_p75:       {num: init_appstart_sessions_p75,      den: init_appstart_sessions}
  init_appstart_session_percent_p95:       {num: init_appstart_sessions_p95,      den: init_appstart_sessions}
  init_duration:                           {num: cnt_init_duration,               den: init_duration_events}
  init_percent_p25:                        {num: init_events_p25,                 den: init_events}
  init_percent_p50:                        {num: init_events_p50,                 den: init_events}
  init_percent_p75:                        {num: init_events_p75,                 den: init_events}
  init_percent_p95:                        {num: init_events_p95,                 den: init_events}
  init_session_duration:                   {num: cnt_init_session_duration,       den: init_session_duration_events}
  init_session_percent_p25:                {num: init_sessions_p25,               den: init_sessions}
  init_session_percent_p50:                {num: init_sessions_p50,               den: init_sessions}
  init_session_percent_p75:                {num: init_sessions_p75,               den: init_sessions}
  init_session_percent_p95:                {num: init_sessions_p95,               den: init_sessions}
  init_session_percent_sla:                {num: init_sessions_sla,               den: init_sessions}
  localloading_duration:                   {num: cnt_localloading_duration,       den: localloading_duration_events}
  localloading_percent_p50:                {num: localloading_events_p50,         den: localloading_events}
  localloading_percent_p75:                {num: localloading_events_p75,         den: localloading_events}
  localloading_percent_p95:                {num: localloading_events_p95,         den: localloading_events}
  localloading_session_duration:           {num: cnt_localloading_session_duration, den: localloading_session_duration_events}
  prepare_duration:                        {num: cnt_prepare_duration,            den: prepare_duration_events}
  prepare_percent_exceptions:              {num: prepare_exceptions,              den: prepare_events_prepare_exceptions}
  prepare_percent_p50:                     {num: prepare_events_p50,              den: prepare_events}
  prepare_percent_p75:                     {num: prepare_events_p75,              den: prepare_events}
  prepare_percent_p95:                     {num: prepare_events_p95,              den: prepare_events}
  prepare_session_duration:                {num: cnt_prepare_session_duration,    den: prepare_session_duration_events}
  serverloading_duration:                  {num: cnt_serverloading_duration,      den: serverloading_duration_events}
  serverloading_percent_exceptions:        {num: serverloading_exceptions,        den: serverloading_events_serverloading_exceptions}
  serverloading_percent_p25:               {num: serverloading_events_p25,        den: serverloading_events}
  serverloading_percent_p50:               {num: serverloading_events_p50,        den: serverloading_events}
  serverloading_percent_p75:               {num: serverloading_events_p75,        den: serverloading_events}
  serverloading_percent_p95:               {num: serverloading_events_p95,        den: serverloading_events}
  serverloading_session_duration:          {num: cnt_serverloading_session_duration, den: serverloading_session_duration_events}

