definitions:
  - &fatal_error                  {eid: 3456}
  - &not_found_error              {error_type: not found}

metric.counter:
  fatal_app_errors:               {filter: [*fatal_error]}
  not_found_errors:               {filter: [*not_found_error]}

metric.uniq:
  users_fatal_app_errors:         {counter: fatal_app_errors,        key: [cookie_n]}
  user_not_found_errors:          {counter: not_found_errors,        key: [cookie]}
